### ISSUE TITLE
[Feature-384 Sparse] Printing of DCSR_matrix

### ISSUE THREAD

**Issue by Mystic-Slice** [helmholtz-analytics/heat#1040]
**Related**
Pending work in https://github.com/helmholtz-analytics/heat/pull/1028

**Feature functionality**
Decide and implement a format for displaying `DCSR_matrix`

**Comment by yash2798** [comment]
Hello @Mystic-Slice , I want to work on this issue. Can you assign this to me?
Thanks a lot!

**Comment by Mystic-Slice** [comment]
Hi @yash2798. Thanks for your interest.
Yes, please feel free to work on this and create a PR once you are done.

Try looking at how printing works in DNDarray for help in the implementation aspect. 
Also, look at the output of different libraries for their sparse matrix formats (especially scipy and torch) and create a format that you think will fit this library. Let us make any modifications later if needed.

**Comment by mrfh92** [comment]
Stil open and relevant; related PR is ongoing work. 
(Reviewed within #1109)
