### ISSUE TITLE
[Bug]: `ht.inv()` tests fail with PyTorch 1.13

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1049]
### What happened?

See PR #1048, assertion test fails already on 1 process:  

```
heat/core/linalg/tests/test_basics.py ...F............ 
```

### Error message or erroneous outcome

```shell
__________________________ TestLinalgBasics.test_inv ___________________________
self = <heat.core.linalg.tests.test_basics.TestLinalgBasics testMethod=test_inv>
    def test_inv(self):
        # single 2D array
        # pytorch
        ares = ht.array([[2.0, 2, 1], [3, 4, 1], [0, 1, -1]])
    
        a = ht.array([[5.0, -3, 2], [-3, 2, -1], [-3, 2, -2]])
        ainv = ht.linalg.inv(a)
    
        self.assertEqual(ainv.split, a.split)
        self.assertEqual(ainv.device, a.device)
        self.assertTupleEqual(ainv.shape, a.shape)
>       self.assertTrue(ht.allclose(ainv, ares))
E       AssertionError: False is not true
heat/core/linalg/tests/test_basics.py:238: AssertionError
```

### Version

1.2.x

### Python version

3.8

### PyTorch version

1.13

### MPI version

```shell
OpenMPI v??
```

**Comment by mtar** [comment]
Looks like an issue introduced in PyTorch 1.13.0 to me. In this particular test, we call its function directly and don't modify the result.

**Comment by ClaudiaComito** [comment]
@JuanPedroGHM  thanks for volunteering to look into this.

I've increased the tolerance of the `allclose()` calls in `linalg.tests.test_basics.TestLinalgBasics.test_inv` #1048 , so the tests run now. It still would be great to pinpoint what exactly in the PyTorch update causes the loss of precision in the example above. Thanks! 🙏🏼

**Comment by ClaudiaComito** [comment]
Thanks a lot @JuanPedroGHM . 

So to summarize, we don't know for sure what in PyTorch 1.13 causes the precision loss, for now our workaround is to increase the tolerance in `allclose()` assertion tests.

I'm closing this issue for now, thanks everybody.
