### ISSUE TITLE
Provide Heat conda build

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1050]
**Feature functionality**

Install heat via  `conda install -c conda-forge heat`  with all dependencies incl. `openmpi`

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by dfsp-spirit** [comment]
That would be very helpful for us at [syncopy](https://github.com/esi-neuroscience/syncopy) as well.

**Comment by swaptr** [comment]
@ClaudiaComito Here is the [PR](https://github.com/conda-forge/staged-recipes/pull/21933).  
1. Are you interested in being a maintainer?
2. Can you review the PR?

**Comment by ClaudiaComito** [comment]
@swaptr wow thanks a lot, we really appreciate this! I'll review the recipe, some packages are missing. 

Yes I'll be a maintainer. @mtar and @bhagemeier please also confirm you're interested in being maintainers.

@swaptr I hope you understand that we need all the conda build maintainers to be members of the core team. Are you ok with not being a maintainer for now? 

Thank you so much!

**Comment by swaptr** [comment]
I added all the development packages, if you want me to remove any packages let me know.
Yes, its absolutely fine.

**Comment by ClaudiaComito** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [conda build interaction with swaptr](https://trello.com/c/Ej9NwSde/5-conda-build-interaction-with-swaptr)

**Comment by ClaudiaComito** [comment]
Hi @swaptr , there are some problems in the recipe. Do you know how to specify channels for specific packages? (I don't) For example, pytorch and torchvision should be installed from channel `pytorch`.

Also, there's this weird error in the [linux build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=653263&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823):
```
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh
```
I've found a recipe that had the same problem and points to an OpenMPI quirk, can you look into this?

https://github.com/conda-forge/staged-recipes/pull/19565


Thanks a lot!

@mtar is following here too

**Comment by swaptr** [comment]
@ClaudiaComito thank you so much for pinning the recipe, it was very helpful. I got down the CI fails only for `windows`, which is supposed to be expected. Do I skip the build for this platform?

**Comment by ClaudiaComito** [comment]
I have created a new conda-forge [PR](https://github.com/conda-forge/staged-recipes/pull/23635) for heat 1.3.

@mrfh92 @JuanPedroGHM whenever you have time, can you comment under the PR that you agree to be maintainers?

With special thanks to @swaptr for showing us how it's done 🙏🏼

**Comment by mrfh92** [comment]
Yes, I agree to be a maintainer :+1: 
And thanks @ClaudiaComito and @swaptr for setting this up 👍

**Comment by ClaudiaComito** [comment]
Thanks Fabian. Please comment on the conda-forge PR as well 😬 see link above

**Comment by mrfh92** [comment]
done :+1:

**Comment by ClaudiaComito** [comment]
Update: I have finalized the conda-forge PR and requested review, it might take a long time.

**Comment by mtar** [comment]
I'm closing this issue. Package can be found here:
- https://anaconda.org/conda-forge/heat
- https://github.com/conda-forge/heat-feedstock
