### ISSUE TITLE
[Feature-384 Sparse] `to_sparse()` method for `DNDarray` class

### ISSUE THREAD

**Issue by Mystic-Slice** [helmholtz-analytics/heat#1054]
**Related**
Pending work from https://github.com/helmholtz-analytics/heat/pull/1028

**Feature functionality**
Implement a `to_sparse()` method for the `DNDarray` class to create a `DCSR_matrix`.

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice I am interested to work on this issue.

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice in this we basically have to convert DNDarray to DCSR_Matrix

**Comment by Mystic-Slice** [comment]
@Ishaan-Chandak Thanks for your interest!
Yes
We have `torch.Tensor`s inside a `DNDarray`. I think this method can simply just call `ht.sparse.sparse_csr_matrix` on the individual tensors(`dndarray.larray`) with the appropriate `is_split` parameter value.

Also, make sure that the `DNDarray` is balanced before doing this since the sparse module for now does not handle imbalance between processes.

When you make a PR for this, try filling out the form provided so that the PR holds complete information about your change/addition.

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice Thanks for the answer.
I have one more question that where should I add this function i.e. in which file.

**Comment by Mystic-Slice** [comment]
It would make sense to add this in `heat/core/manipulations.py`

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice just an update, I  am reading the docs of heat for better understanding and i have managed to write some code. Currently I am not sure whether it is correct or not I will try to run that with some modifications and then send the final results here.

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice can you help me find some test cases to help me check whether the program I have written is correct or not.

**Comment by Mystic-Slice** [comment]
Hey! @Ishaan-Chandak. Sorry for the late reply.
You can test it using something like 
```py
arr = [ [0, 0, 1, 0, 2]
        [0, 0, 0, 0, 0]
        [0, 3, 0, 0, 0]
        [4, 0, 0, 5, 0]
        [0, 0, 0, 0, 6] ]

A = ht.array(arr, split=0) # DNDarray

B = ht.array(arr, split=0).to_sparse() # DCSR_matrix

assert (A.larray.to_sparse_csr() == B.larray)
```

I of course have not tested this code, but you must be able to verify the `to_sparse()` method this way.

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice I am not sure why this error is popping up can you please help me resolving this issue.

![Screenshot from 2023-03-06 17-58-34](https://user-images.githubusercontent.com/103961770/223110679-80136946-770d-445e-a7f1-82f92f4d5f9a.png)

**Comment by Mystic-Slice** [comment]
I am not completely sure, but it might be because you are inside the `heat/heat/sparse/` folder. Try running this from the root folder of the project.

**Comment by samadpls** [comment]
Hey @Mystic-Slice, could you please assign this to me?
