### ISSUE TITLE
Avoid unnecessary `gather`ing of distributed operand in mixed distributed/non-distributed `logical` functions

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1064]
**Feature functionality**

module `heat.core.logical`, functions `allclose(x,y)`, `isclose(x,y)` 

Currently, when only one of the operands is distributed, these functions (via `__sanitize_close_input`) [gather](https://mpitutorial.com/tutorials/mpi-scatter-gather-and-allgather/) the distributed operand and perform the global comparison on each process. 

Modify the relevant functions to carry out the comparison on the relevant slice of non-distributed operand instead.

**Comment by Ishaan-Chandak** [comment]
Hi @ClaudiaComito  is this issue still open ?

**Comment by mrfh92** [comment]
This issue is stil open and useful. 

(Reviewed within #1109)

**Comment by samadpls** [comment]
Hey @ClaudiaComito and @mrfh92, can I work on this issue?
