### ISSUE TITLE
Improve Alltoallv documentation of `sendbuf`, `recvbuf`

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1072]
**Feature functionality**

Currently, our documentation is pretty much identical for `communication.Alltoall` and `communication.Alltoallv`. 

Improve `communication.Alltoallv` docs to indicate different construction of `sendbuf`, `recvbuf`. 

**Additional context**
[OpenMPI Alltoallv](https://www.open-mpi.org/doc/v4.0/man3/MPI_Alltoallv.3.php) vs. [Alltoall](https://www.open-mpi.org/doc/v4.0/man3/MPI_Alltoall.3.php)

**Comment by Ishaan-Chandak** [comment]
Hi !
I would like to please work on this issue.

**Comment by ClaudiaComito** [comment]
Perfect, @Ishaan-Chandak go ahead!

**Comment by Ishaan-Chandak** [comment]
Thank you soo much @ClaudiaComito
