### ISSUE TITLE
[Bug]: Communicator not properly initialized when creating new DNDarrays in some routines

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1074]
### What happened?

In some HeAT routines, e.g. `matmul`, the initialization of new DNDarrays (usually the output of the routine) is done without specifying a communicator for the new DNDarray properly. Consequently, the default communicator `MPI.COMM_WORLD` is used which can result in errors when dealing with DNDarrays on different subgroups of `MPI.COMM_WORLD` in parallel. 

In `matmul` the output array `c = a @ b` is initialized as 
```
c = factories.zeros(c_shape, split=a.split, dtype=c_type, device=a.device)
```
or similar (at various places). I suggest to add here and at comparable places `comm=a.comm` as argument since this fixes the bug.  

### Code snippet triggering the error

```shell
"""
Run with 4 MPI processes 
"""

import heat as ht
import numpy as np  
from mpi4py import MPI

global_comm = MPI.COMM_WORLD 
nprocs = global_comm.Get_size()

# create two subgroups of COMM_WORLD
idx_group_1 = [i for i in range(nprocs) if i >= nprocs/2]
idx_group_2 = [i for i in range(nprocs) if i < nprocs/2]
group_1 = global_comm.group.Incl(idx_group_1)
group_2 = global_comm.group.Incl(idx_group_2)
comm_1 = ht.MPICommunication(global_comm.Create_group(group_1))
comm_2 = ht.MPICommunication(global_comm.Create_group(group_2))

if global_comm.rank in idx_group_1:
    m = 4
    n = 2
    dtype = ht.float64
    comm=comm_1
    split=0
elif global_comm.rank in idx_group_2:  
    m = 3
    n = 6 
    dtype = ht.float32
    comm=comm_2
    split=1

A = ht.random.randn(m,n,dtype=dtype,comm=comm,device='cpu',split=split)

# this does not work 
B = A.T @ A
```

### Error message or erroneous outcome

```shell
Traceback (most recent call last):
  File "group_examples.py", line 55, in <module>
    C = A.T @ A
  File "/home/hopp_fa/heat/heat/core/linalg/basics.py", line 1104, in <lambda>
    DNDarray.__matmul__ = lambda self, other: matmul(self, other)
  File "/home/hopp_fa/heat/heat/core/linalg/basics.py", line 1060, in matmul
    c.larray[: sp0 - st0, st1:sp1] += a.larray @ b_lp_data[pr - 1]
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0
```

### Version

1.2.x

### Python version

3.8

### PyTorch version

1.12

### MPI version

```shell
mpi4py Version: 3.1.3
```

**Comment by AsRaNi1** [comment]
Hi
I would please like to work on this issue!

**Comment by ClaudiaComito** [comment]
Hi @AsRaNi1 ,

perfect, go ahead! I'm going to assign the issue to you.

I've put together some [Quick Start](https://github.com/helmholtz-analytics/heat/blob/main/quick_start.md) instructions, please let me know if something is unclear so we can fix it.

**Comment by AsRaNi1** [comment]
@ClaudiaComito Yes sure!

**Comment by AsRaNi1** [comment]
@ClaudiaComito are there any build tests that is should know of i am supposed to run?

**Comment by ClaudiaComito** [comment]
> 
@AsRaNi1 I've updated [Quick Start](https://github.com/helmholtz-analytics/heat/blob/main/quick_start.md) with unit tests instructions.
