### ISSUE TITLE
[Bug]: `ht.sparse.sparse_csr_matrix` does not validate number of dimensions in input

### ISSUE THREAD

**Issue by Mystic-Slice** [helmholtz-analytics/heat#1091]
### What happened?

`ht.sparse.sparse_csr_matrix` should accept only 2-D input. But it accepts (and crashes) when the input is not 2 dimensional. 

The input must be properly validated to ensure only 2-D input is accepted. Or else an error with the message "The number of dimensions must be 2, found `ndim`" must be raised.

### Code snippet triggering the error
```
import heat as ht
import torch

a = torch.tensor([0, 1]) # 1-D input
print(a)
t = ht.sparse.sparse_csr_matrix(a)
print(t)
```

### Error message or erroneous outcome

```
tensor([0, 1])
Traceback (most recent call last):
  File "xexample.py", line 16, in <module>
    t = ht.sparse.sparse_csr_matrix(a)
  File "/mnt/e/Opensource/heat/heat/sparse/factories.py", line 130, in sparse_csr_matrix
    obj = obj.to_sparse_csr()
RuntimeError: expand(torch.LongTensor{[1, 2]}, size=[2]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
```

### Version

1.2.x

### Python version

3.8

### PyTorch version

1.13

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice I want to work on this issue can you assign the issue to me.

**Comment by Mystic-Slice** [comment]
Hey @Ishaan-Chandak. Go ahead!
Ask here if you have any doubts.

**Comment by Ishaan-Chandak** [comment]
Hii @Mystic-Slice I worked on this issue and  can u check whether this output is required or not

![Screenshot from 2023-02-08 11-52-06](https://user-images.githubusercontent.com/103961770/217451284-a71580d4-c8b3-48a9-ba90-2129557d5906.png)

**Comment by Mystic-Slice** [comment]
Hey @Ishaan-Chandak. Yes, you are almost there!
In the output message, the `ndim` should actually show the number of dimensions in the input object. 

For example, if the input is a 1D tensor, the message should read
"The number of dimensions must be 2, found 1"

This will give the user more info about where the problem is.

**Comment by Mystic-Slice** [comment]
After you are done with this, please feel free to create a PR and tag me there.

**Comment by Ishaan-Chandak** [comment]
Okays I'll make the necessary changes and send the PR

**Comment by Ishaan-Chandak** [comment]
Hii @Mystic-Slice I have made the necessary changes, so can you verify this output 
![Screenshot from 2023-02-08 15-16-30](https://user-images.githubusercontent.com/103961770/217494563-05998618-6c46-4840-8f61-abe3b0bc7ed8.png)

**Comment by Mystic-Slice** [comment]
@Ishaan-Chandak Yeah. Looks good.
Go ahead and create the PR.

**Comment by Ishaan-Chandak** [comment]
Hi @Mystic-Slice I have sent the PR please review it.
Thank you
