### ISSUE TITLE
Provide a solver for triangular systems

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1096]
**Feature functionality**
Provide a solver for the linear equation $Ax = b$, where $b \in \mathbb{K}^{m \times n}$, $A \in \mathbb{K}^{m \times m}$ are two-dimensional `DNDarrays` such that $A$ is either upper- or lower-triangular. 

Intended scope: 
- different combinations of `split` for $A$ and $b$
- of course, scalability of the routine is desired

**Additional context**
* Often required in combination with Cholesky decompositon #886 
* also required in context of linear regression (implementing a "QR + triangular solve"-based linear regressor for massive data could be a cool second part of a corresponding student project or PR)

**Comment by mrfh92** [comment]
I would suggest to put `triangular_solve` into `.../solver.py` and to create a new file `/core/linalg/cholesky.py` for `cholesky`

**Comment by Gaurav17Joshi** [comment]
Hi, I have created a new function triangular_solver in .../solver.py. It takes in A and B as inputs and returns the solution x for Ax = B, also, this function raises error flag if the user does not input a triangular matrix or the matrix is not full rank.

<img width="458" alt="lower matrix (No split)" src="https://user-images.githubusercontent.com/111291834/218690475-a0503aac-e7f8-4f78-950d-f4ffb4739afe.png">

<img width="458" alt="lower matrix (Split)" src="https://user-images.githubusercontent.com/111291834/218690705-a6743558-08e0-41bd-81f2-6303b8cc8227.png">

<img width="524" alt="upper matrix (No split)" src="https://user-images.githubusercontent.com/111291834/218690764-89851118-932c-4ccf-97f9-db37f1a47968.png">

<img width="474" alt="upper matrix (split)" src="https://user-images.githubusercontent.com/111291834/218690791-5984285d-94c4-477f-84d7-24f840f1d57d.png">

**Comment by Gaurav17Joshi** [comment]
Raising Errors:
<img width="703" alt="Not Triangular" src="https://user-images.githubusercontent.com/111291834/218691028-a192f206-9957-4dc7-abd2-fff1746b068e.png">
<img width="700" alt="Not Full rank" src="https://user-images.githubusercontent.com/111291834/218691045-0e9c0c47-88b5-4543-b4da-80a6ac7e3c4a.png">

**Comment by Gaurav17Joshi** [comment]
@mrfh92 , can I create a PR so , that my code can be reviewed.

**Comment by mrfh92** [comment]
Stil open and relevant 
(Reviewed within #1109)

**Comment by mrfh92** [comment]
Some first thoughts on this are found in the #1236

**Comment by mrfh92** [comment]
@FOsterfeld works on this within #1236

**Comment by mrfh92** [comment]
Implemented and merged in #1236 by @FOsterfeld

**Comment by mrfh92** [comment]
see #1433 for the error messages

**Comment by mrfh92** [comment]
Has been completed actually.
