### ISSUE TITLE
Provide templates for performance monitoring 

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1099]
When monitoring parallel performance of new/existing routines, it will be helpful to have templates for executing the corresponding benchmark tests: 
* run on an increasing number of CPUs (with fixed number of threads per MPI-process)
* run on an increasing number of GPUs
* run on a fixed number of CPUs with different combinations of number of MPI-processes and number of threads per process

**Comment by ClaudiaComito** [comment]
Potentially interesting for @JuanPedroGHM as well

**Comment by mrfh92** [comment]
see PR #1100

**Comment by ClaudiaComito** [comment]
Alright let me see if I understand everything:

1. #1100 led by @mrfh92  is meant to standardize scaling tests for features / bug fixes during development 
2. @JuanPedroGHM 's GSoC23 project is meant to create a repository of scaling tests (benchmarks?) for a collection of released features (project details TBD, will link here when ready)

Is this correct?

If so, it would be great to design things a way that we can seamlessly plug a "development" scaling test from 1. into our scaling tests / benchmarks collection 2.

**Comment by mrfh92** [comment]
This is true... in fact there has already been created a more involved version of my templates in branch #584... actually, what I provided here is just a template that avoids to write new slurm script every time 
But there is no automation etc. ...
