### ISSUE TITLE
[Bug]: ReadTheDocs link on `release/1.2.x` points to docs on `main` branch

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1101]
### What happened?

The README on the `release/1.2.x` branch points to our development (`main` branch) documentation, hence also our documentation on PyPi does not match the latest release, but the future major release.

Note for **new contributors**: 

- please branch off the  `release/1.2.x` branch to fix this issue, not the `main` branch. 
- when you create a PR, make sure your base branch (the branch you want to merge your change into) is `release/1.2.x`, not `main`.

Thanks a lot!

<img width="776" alt="Screenshot 2023-02-13 at 11 08 47" src="https://user-images.githubusercontent.com/39374113/218429599-ae3111b8-8367-4ee0-9ee9-03fba8d11fe0.png">

### Version

1.2.x

### Python version

None

### PyTorch version

None

**Comment by yash2798** [comment]
Hello @ClaudiaComito, I can help resolve this issue! Can I ask some questions?

**Comment by ClaudiaComito** [comment]
Go ahead! This should be a tiny change, please submit a PR directly and we can discuss open questions there. Thank you so much!

**Comment by Sai-Suraj-27** [comment]
@ClaudiaComito I want to fix this, From what I understood the link for ReadTheDocs in the `release/1.2.x` branch is pointing to the [latest](https://heat.readthedocs.io/en/latest/) version of the docs and it should be changed to this [stable](https://heat.readthedocs.io/en/stable/) version. Is that it? or is there anything else I should add while making a PR?

**Comment by ClaudiaComito** [comment]
That is correct @Sai-Suraj-27, it really is a tiny change

**Comment by Sai-Suraj-27** [comment]
@ClaudiaComito Mam, I think this issue can be closed.

**Comment by ClaudiaComito** [comment]
Closing, thanks @Sai-Suraj-27
