### ISSUE TITLE
Improve API reference

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1102]
**Context**
Heat's [autogenerated API reference](https://heat.readthedocs.io/en/latest/autoapi/index.html)  lists all the modules in alphabetical order and links to the modules' documentation. 

This is perfect for us insiders, but a bit confusing for users who go through the API reference to figure out what numpy or scikit-learn functionalities they can memory-distribute with Heat. 

**Feature functionality**
Replace or augment our API reference with something that conveys at a glance what numpy/scipy functions or scikit-learn algos are already implemented in Heat, what features are in progress (would be nice: link issue/PR?),  what are missing entirely (would be nice: link/button to request feature).

**Additional context**
For inspiration:
[dpnp](https://intelpython.github.io/dpnp/reference/index.html)
[ramba](https://github.com/Python-for-HPC/ramba#numpy-compatibility)
[cunumeric](https://nv-legate.github.io/cunumeric/23.01/api/index.html)

Feel free to add more in the comments.

**New contributors**

- please branch off the  `release/1.2.x` branch to fix this issue, not the `main` branch. 
- when you create a PR, make sure your base branch (the branch you want to merge your change into) is `release/1.2.x`, not `main`.

Thanks a lot!

**Comment by AsRaNi1** [comment]
@ClaudiaComito I would like to work on this issue, i'll soon create a PR

**Comment by ClaudiaComito** [comment]
@AsRaNi1 thanks a lot for taking this on. Ideally we  would have: 
- an automated or semi-automated solution including everything
- a summary table with the most important modules/functions that we can post on the README.

Summary table would be top priority at this time.

Thanks again!
