### ISSUE TITLE
[Bug]: (possible bug) suspicious scaling behaviour of load  

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1140]
### What happened?

The function `heat.load` seems to behave quite different w.r.t. scaling depending on whether `split=0` or `split=1`. 
I tested with a $\approx$ 20GiB data set on different machines and for CPU and GPU and observed the following behaviour: 

![load_cpu_caro](https://user-images.githubusercontent.com/112093564/232054872-f3cc9bc4-72d2-4748-97e0-151cda051448.jpg)
![load_cpu_hdfml](https://user-images.githubusercontent.com/112093564/232054881-dfb89bc9-6dd3-4c05-82d8-c75704d19680.jpg)
![load_cpu_terrabyte](https://user-images.githubusercontent.com/112093564/232054887-f8a4eb33-1c0b-4582-af24-f6c38e04e93a.jpg)
![load_gpu_hdfml](https://user-images.githubusercontent.com/112093564/232054891-4f543cf6-a8b9-468f-8aef-38db1c33554e.jpg)
![load_gpu_terrabyte](https://user-images.githubusercontent.com/112093564/232054894-65b3f1d3-1a40-4c64-94da-27e3dd5cd59b.jpg)

In my opinion this indicates that `split=0` works quite fine whereas there might be room for improvements for `split=1`. 

### Version

1.2.x

### Python version

None

### PyTorch version

None

**Comment by ClaudiaComito** [comment]
@mrfh92 interesting, what data format? `ht.load` calls `ht.load_hdf5` or `ht.load_netcdf4` or `ht.load_csv` internally.

**Comment by mrfh92** [comment]
It was a `.h5`-file

**Comment by mrfh92** [comment]
I have repeated the experiment on a CPU-cluster with a data set of roughly 180GB size; time is the average over 5 runs each. 
![load_cpu_terrabyte](https://github.com/helmholtz-analytics/heat/assets/112093564/95b2c63b-4130-450a-92e5-d59bcdb80322)

I think it is quite obvious that something is going wrong for `split=1`...

**Comment by mrfh92** [comment]
@ClaudiaComito I have looked up, whether the data sets used for this experiments have been stored in chunked format in the h5-file via checking the `chunks`-attribute of the data sets: 
```
file = h5py.File('filename.h5','r')
print(file['dataset_name'].chunks)
```
In all cases this has been `None`. Do you have experience whether this could be responsible for the strange behaviour?
