### ISSUE TITLE
Adopt NEP 29

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1146]
**Related**
#1145 #1142 #1144 

**Feature functionality**
Adopt Numpy / PyTorch scheme for Python and NumPy version support.

[NEP 29 — Recommend Python and NumPy version support as a community policy standard — NumPy Enhancement Proposals](https://numpy.org/neps/nep-0029-deprecation_policy.html)

[pytorch/RELEASE.md at 893aa5df3f2a475c91ea8eadb1353812e52fb227 · pytorch/pytorch](https://github.com/pytorch/pytorch/blob/893aa5df3f2a475c91ea8eadb1353812e52fb227/RELEASE.md#python)

**Comment by ClaudiaComito** [comment]
NEP29 compliance for v1.4 assessment by T-14   (Jan 18th 2024)

**Comment by mrfh92** [comment]
https://github.com/hmaarrfk/nep29 could be an option for automatization
