### ISSUE TITLE
in-place operators for `arithmetics.py`

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#1184]
**Related**
The memory/time may be saved by using in-place functions.

**Feature functionality**
Implement in-place functions for some local operations.

**Additional context**
https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html?highlight=add_#torch.Tensor.add_
https://docs.python.org/3/reference/datamodel.html#object.__iadd__

**Comment by ClaudiaComito** [comment]
What in-place operations are we missing? Most if not all ops in `arithmetics` have already an in-place version.
