### ISSUE TITLE
[Bug]: Badge says that docs are failing

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1185]
### What happened?

Quite recently (I dont know when exactly) the badge for docs in our README.md changed to "failing"

### Version

1.2.x

### Python version

None

### PyTorch version

None

**Comment by mtar** [comment]
https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by ClaudiaComito** [comment]
closed by #1187
