### ISSUE TITLE
[Bug]: Vulnerability report is broken

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1225]
### What happened?

We introduced the option to report security vulnerabilities and created a dedicated issue template.

https://github.com/helmholtz-analytics/heat/issues/new/choose

At the moment, reporting the vulnerability doesn't work: the link that should open the vulnerability report template (see above) points to the security policy, which in turn invites to report  via the template.

There were some errors in the template which I have fixed in #1205, but I'm not sure that will solve the loop.

### Version

1.3.x

### Python version

None

### PyTorch version

None

**Comment by mrfh92** [comment]
![grafik](https://github.com/helmholtz-analytics/heat/assets/112093564/f56ff062-33a1-464c-be74-78ccd6d423ef)

**Comment by mrfh92** [comment]
Meanwhile I have merged #1205 (thanks for the work done there :+1:) and requesting a new issue now looks as follows: 
![Screenshot (33)](https://github.com/helmholtz-analytics/heat/assets/112093564/f458967b-3131-4e6a-8817-577e5b1c89d5)

**The button to open the vulnerability issue template works correctly**, so the loop is solved. We only need to decide whether we want to remove the additional link to the security policy below.

**Comment by ClaudiaComito** [comment]
I'd say this is closed and we can beautify at the next README update iteration. Thanks!
