### ISSUE TITLE
[Bug]: Benchmarking results are not plotted / Action `cb/report` pending without BenchmarkPR-label

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1226]
### What happened?

After mergin #1220 I have observed: 

* that at least the benchmark results for the two newest merges (#1220 and #1186) have not been plotted. The last plotted benchmark results belong to #1221 
* The action `cb/report` is shown as pending (and seems not to finish so far) although there is no BenchmarkPR-label (see, e.g., #1218 and #1175 - I had merged main there after merging #1220 so the CI should be up-to-date in these branches) 

Remark: to check whats going on I have added a BenchmarkPR-label to the FFT-branch, bow it works correctly (but fails), pending status without BenchmarkPR label is still visible in #1175.

### Version

1.3.x

### Python version

None

### PyTorch version

None

**Comment by JuanPedroGHM** [comment]
Working on it
