### ISSUE TITLE
[Bug]: New Pytorch Release workflow fails

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1241]
### What happened?

Manually triggered GH Action [Get latest PyTorch version main branch](https://github.com/helmholtz-analytics/heat/actions/workflows/pytorch-latest-main.yml) fails.

### Error message or erroneous outcome

```shell
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
  Error: The process '/usr/bin/git' failed with exit code 128
```

### Version

1.3.x

### Python version

None

### PyTorch version

None

### MPI version

```shell
doesn't matter
```

**Comment by mrfh92** [comment]
Is this related to checking compatibility with PyTorch 2.1 and CUDA 12.2 (=CUDA-version on Stage2024 on HDFML)?

**Comment by ClaudiaComito** [comment]
This is still open. The workflow is supposed to push the latest pytorch version to the newly created branches, the push must trigger `latest_pytorch_support.yml` which creates the PRs.

@mtar ping me if you cannot work on this today, I'll take over.
