### ISSUE TITLE
Implement modf()

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#125]

**Comment by coquelin77** [comment]
is this intended to be the same as torch.fmod?

**Comment by TheSlimvReal** [comment]
I suppose this can be closed due to #196 which implemented mod and fmod?

**Comment by Markus-Goetz** [comment]
This is indeed different from fmod() as it returns fractional and integral part. See also

https://docs.scipy.org/doc/numpy/reference/generated/numpy.modf.html
