### ISSUE TITLE
[Bug]: outdated Heat version in Docker file

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1254]
### What happened?

The Docker file and related documentation on branch `release/1.3.x` refers to an older version of Heat.

ToDo:

- [ ] update Docker file and all documentation
- [ ] add related step to RELEASE.md file so we don't forget again

### Version

1.3.x

### Python version

None

### PyTorch version

None

**Comment by ClaudiaComito** [comment]
addressed in #1178

**Comment by mrfh92** [comment]
Corresponding fix has been merged in release and main.
