### ISSUE TITLE
Implement round()

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#126]

**Comment by coquelin77** [comment]
should this be the same implementation as torch? they only have round to nearest integer

**Comment by Markus-Goetz** [comment]
Can be a nearest integer rounding first, aka decimals=0 hard coded. However, in the end we should provide an arbitrary decimal place rounding.

Possible implementation strategy:

* Subtract modf() value with divisor being the proper power of 10 based on decimals
