### ISSUE TITLE
[Bug]: Continuous benchmarks fail for QR due to deprecated value for tiles_per_proc

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1330]
### What happened?

see title
for an example see #1228 

### Code snippet triggering the error

```shell
.
```

### Error message or erroneous outcome

```shell
.
```

### Version

1.3.x

### Python version

None

### PyTorch version

None

### MPI version

```shell
.
```

**Comment by mtar** [comment]
It looks like the the warning is not set correctly.

**Comment by mrfh92** [comment]
Now, the warning is crash-free in #1331 
Nevertheless, I removed QR with tiles_per_proc=1 from the benchmarks since we actually deprecated this functionality
