### ISSUE TITLE
Implement vmap

### ISSUE THREAD

**Issue by JuanPedroGHM** [helmholtz-analytics/heat#1383]
**Related**
Provide a clean way to apply NumPy or torch functions to the local arrays, without having to manually get the local array, transform it to torch/NumPy, apply the function and then create the DNDArray again.

**Feature functionality**
The user should be able to apply a function from torch or NumPy in a single command, as long as the result is independent of the global array and the result shape of the local array does not change.

**Comment by mrfh92** [comment]
Is this intended to work similar as, e.g., `torch.vmap` in the sense that you can do something like: 
```
fun = ht.heatmap(torchfun) 
y = fun(x)
```
with a function `torchfun` defined on torch.Tensors?
