### ISSUE TITLE
Declutter automated release notes

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1395]
With the many dependency updates, our [Draft release notes](https://github.com/helmholtz-analytics/heat/releases) are getting a bit cluttered. 

I think it's important to keep track of the CI changes, not sure about all the `dependabot` merges.

What do you think @mtar , @JuanPedroGHM ?

**Comment by mtar** [comment]
I agree, the entries comming from dependabot are not noteworthy. This also goes for pre-commit-ci and step-security-bot
