### ISSUE TITLE
[Bug]: Citation file cannot be parsed

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1427]
### What happened?

While viewing our CITATION.cff file, I noticed this warning:

"Your CITATION.cff file cannot be parsed. Make sure the formatting is correct. [Learn more about CITATION files.](https://docs.github.com/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files)"

TODO:
- [ ] find formatting error
- [ ] expand RELEASE.md to make sure we check the citation file before release
- [ ] (would be nice) implement/adopt automation to detect errors in CITATION.cff - not sure this is possible
 

### Version

main (development branch)

### Python version

None

### PyTorch version

None

**Comment by mtar** [comment]
The same issue is mentioned [here](https://github.com/citation-file-format/ruby-cff/issues/122). Unquoting the dates does the trick.
