### ISSUE TITLE
[Bug]: codecov fails

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1491]
### What happened?

codecov failed to upload its report after merging the new dependencies to `main` this morning. Pipeline fails on `main` and code coverage is at 17%.

### Version

main (development branch)

### Python version

None

### PyTorch version

None

**Comment by bhagemeier** [comment]
I've restricted the permissible versions of PyTorch in commit 7e6a988a.

**Comment by mrfh92** [comment]
Is working again.
