### ISSUE TITLE
Support for the Parquet data format

### ISSUE THREAD

**Issue by wfthi** [helmholtz-analytics/heat#1544]
** Rational **
Large datasets are now often stored in the Parquet format (https://parquet.apache.org). In principle, other packages can read efficiently data in the parquet format.

**Related**

**Feature functionality**

**Additional context**
Packages like DuckDB (https://duckdb.org) can retrieve data  using SQL queries so one can just write her/his own code to use heat with large datasets.

**Comment by krajsek** [comment]
We can add parquet format support to heat. @wfthi Is there any particular dataset that you have in mind that we can use as a test case?

**Comment by wfthi** [comment]
Hi,

Great. One can try https://www.kaggle.com/competitions/leash-BELKA/data
