### ISSUE TITLE
Support masked DNDarrays

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1553]
**Related**
related to RFI mitigation support, see, e.g., #1515 

**Feature functionality**
We want to support masked DNDarrays, similarly to masked NumPy-arrays or masked PyTorch-Tensor, of course based on the latter ones. 
We need: 
* a new class MaskedDNDarray, derived from DNDarray (or can we integrate masking-possibility silently into DNDarray?) 

and the following functions: 
* tbd

**Comment by mrfh92** [comment]
@ClaudiaComito I have created this feature request on marked DNDarrays

**Comment by ClaudiaComito** [comment]
Closing this as duplicated, see #959 .  (Thanks anyway @mrfh92 , will copy the text over)
