### ISSUE TITLE
drop Python 3.8, PyTorch < 2.0

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#1572]
**Related**
Python 3.8 reaches end of support on October.
Drop PyTorch 1.13 too?
Other dependencies need to be checked.

**Comment by mrfh92** [comment]
I would definitely agree with dropping PyTorch 1.13 as 2.0.0 brought many changes (like vmap) that require a workaround with version checks at the moment

**Comment by mrfh92** [comment]
see #1573 removed PyTorch 1.12 and 1.13 as well as Python 3.8 from setup.py and CI-matrix
