### ISSUE TITLE
Refactor test cases that make use of FLOAT_EPSILON to use ht.allclose instead

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#161]

**Comment by Markus-Goetz** [comment]
We should get rid of the FLOAT_EPSILON static variable and instead use the default set in allclose() for this

**Comment by Cdebus** [comment]
Ok, but the default absolute tolerance in allclose is much more strict (1E-8 vs 1E-4).

**Comment by Markus-Goetz** [comment]
That is okay thought. The 1e-4 was an initial assumption to make the tests pass 1e-8 might actually be more of the precision range what we want to achieve anyway.

**Comment by Cdebus** [comment]
Ok, will take care of it
