### ISSUE TITLE
split reductions into sub-files

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#163]
numeric_reductions: mean, var, sum, etc.
logic_reduction: all, argmin, min, max, etc.

**Comment by Markus-Goetz** [comment]
After further discussion in Mattermost, it was suggested to further enhance the above proposal as follow:

numeric_reductions: sum, prod, ....
statistics: mean, argmin, min, max, var, median, ...
logic_reductions: all, allclose, any, ...
