### ISSUE TITLE
Provide in-place binary operations

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#169]
At the moment it is possible to do the following for example:

```
a = ht.zeros((5, 3))
a + 1
```

However, it is impossible to do:

a = ht.zeros((5, 3))
a += 1

HeAT currently does not provide implementation for so-called in-place operations, e.g. `__iadd__` etc.

**Comment by ClaudiaComito** [comment]
Addressed. Closing.
