### ISSUE TITLE
[Bug]: del() does not work as expected 

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1749]
### What happened?

If you apply del() to a DNDarray, the memory is not always freed as expected

### Code snippet triggering the error

```shell
Run this with 2 MPI-processes on 2 GPUs: 

import heat as ht 
import time 

x = ht.random.randn(100000,50000, split=0, dtype=ht.float32, device="gpu")

time.sleep(2)

del(x) 

time.sleep(2) 

print("Memory freed!")
```

### Error message or erroneous outcome

One would expect that the ~10GB of data on each GPU get freed by `del(x)`, but this is not the case as one can find out with perun (sampling_period = 0.1) 

![grafik](https://github.com/user-attachments/assets/de80fd07-925a-4dc5-8665-7764fa2c8fdc)

[This is the memory for the first GPU, but the second shows the same behaviour.]

**Comment by mrfh92** [comment]
With 
```
del(x)
torch.cuda.empty_cache()
```
we get the following:

![grafik](https://github.com/user-attachments/assets/801244e0-e4b7-4cd1-8bb3-f4c0bfa2be91)

**Comment by mrfh92** [comment]
What should be much more a problem to us is that in
```
x = torch.zeros(50000,5000, dtype=torch.float32, device=f"cuda:{ht.MPI_WORLD.rank}")
time.sleep(2)
del(x)
```
also memory is not freed: 

![grafik](https://github.com/user-attachments/assets/d0030e71-b20b-4414-ba3a-7ae594196b0e)

**Comment by Markus-Goetz** [comment]
This is not necessarily a bug, but purely a behavior of the caching memory allocator of PyTorch on GPU, https://pytorch.org/docs/stable/notes/cuda.html#memory-management

**Comment by mrfh92** [comment]
Yes, its not a bug in PyTorch, but a bug in Heat because internally we use del(...) at some points to delete objects that are no more needed and this does not have the required effect without adding `torch.cuda.empty_cache()`.

**Comment by mrfh92** [comment]
ok, I understand now its only a measurement problem as nvidia-smi sees that as allocated memory but PyTorch (and thus Heat) knows that its free for allocating further tensors
