### ISSUE TITLE
Realize Travis build matrix for optional heat features

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#203]
Heat currently offers optional features, such as HDF5 or NetCDF4. The build system currently only executes tests for the full-fledged Heat installation, however, the test cases for not installed optional features should also be executed and added to the coverage report.

Possible implementation solution, Travis build matrix, for more have a look here:

See also here: https://docs.travis-ci.com/user/build-matrix/

**Comment by TheSlimvReal** [comment]
I will add this step to the GitHub workflow.

**Comment by TheSlimvReal** [comment]
I think the build matrix makes this feature a little to big. Currently the workflow consists of 2 x 4 runs, adding another dimension to the build matrix would increase this to 2 x 4 x 2. Instead I would create another separate job that only builds an tests the code without optional dependencies on a single scenario.
