### ISSUE TITLE
Document MPI wrapper functions

### ISSUE THREAD

**Issue by Cdebus** [helmholtz-analytics/heat#207]
After the #201, there exist new heat wrappers for MPI functions, which can automatically send torch tensors via MPI under consideration of storage offsets, strides, etc. At the same time these wrappers provide a more numpy-like API in the sense that they allow definition of axes along which tensors can be "stacked" and that whole rows/columns are send (along an axis), not only single Bytes/elements.
These functions need proper documentation, regarding the definition of the axes, the underlying process (rolling out tensors) etc

**Comment by mtar** [comment]
Is this issue still up to date?

**Comment by ClaudiaComito** [comment]
Documentation exists. Closing.
