### ISSUE TITLE
Provide fft()

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#241]

**Comment by mtar** [comment]
These packages may be useful:
- [mpi4py-fft](https://mpi4py-fft.readthedocs.io/en/latest/)
- [FluidFFT](https://fluidfft.readthedocs.io/en/latest/index.html)

**Comment by dfsp-spirit** [comment]
This would be very much appreciated indeed, as discussed with @ClaudiaComito.

**Comment by ClaudiaComito** [comment]
closing this as duplicate of #1097
