### ISSUE TITLE
Provide cum* operation

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#243]
Implementation suggestion: MPI_Scan/MPI_Exscan()

* cumprod() and alias cumproduct()
* cumsum()

**Comment by TheSlimvReal** [comment]
The cases where `axis == split` and `axis != split and axis is not None` are quite clear. But for `axis is None` do we want the result to still be distributed (It's the cumsum/cumprod of the flattened array)?
