### ISSUE TITLE
misused __binary_op in ht.equal

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#274]
Example:
T1 = ht.float32([[1, 2],[3, 4]])
T2 = ht.float32([[2, 2], [2, 2]])
ht.equal(T1, T2)
results in inconsistent preliminary results in ht.equal:
result_tensor = operations.__binary_op(torch.equal, t1, t2)
result_tensor._DNDarray__array = False is a boolean scalar but
result_tensor.gshape = (2, 2)

**Comment by krajsek** [comment]
Example:   
T1 = ht.float32([[1, 2],[3, 4]])                                                                              
T2 = ht.float32([[2, 2], [2, 2]]) 
ht.equal(T1, T2)
results in inconsistent  preliminary results in ht.equal:
result_tensor = operations.__binary_op(torch.equal, t1, t2)
result_tensor._DNDarray__array = False is a boolean scalar but
result_tensor.gshape = (2, 2)

**Comment by Markus-Goetz** [comment]
This function actually implements torch's way of equal, i.e. overall equality of tensors, and not numpy's way. You would get numpy's implementation by using the '==' operator. The docstrings for Heat are correct though. Still relevant?

**Comment by krajsek** [comment]
If that's the way it was intended, it's done.
