### ISSUE TITLE
parallel matrix multiplication for non-splitted heat tensors

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#285]
This issue investigates possible optimization strategies to #108

**Comment by Markus-Goetz** [comment]
Duplicate of 108?

**Comment by krajsek** [comment]
This issue investigates possible optimization strategies to #108

**Comment by coquelin77** [comment]
Wouldn't this be taken care of by torch? I was under the impression that torch will parallelize this internally, is this not the case?

Are you suggesting that we should write our own algorithm for this?
