### ISSUE TITLE
bug in __binary_op

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#294]
__binary_op does not handle broadcasting correctly

**Comment by Markus-Goetz** [comment]
What is the issue here again? Do you have an example?

**Comment by krajsek** [comment]
aa=torch.arange(2)
aa.dtype

**Comment by krajsek** [comment]
> 
> 
> What is the issue here again? Do you have an example?

sorry, wrong answer to the issue, I have to look into the code to remind me what is going on

**Comment by ClaudiaComito** [comment]
I'm going to assume that this problem was fixed at the latest by #902. Let us know @krajsek if you run into it again.
