### ISSUE TITLE
bug in array type casting

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#299]
```python
aa = ht.array(np.ones((4, 1)))
print(aa.dtype, aa._DNDarray__array.type())
>>> <class 'heat.core.types.float64'> torch.DoubleTensor
```
ht.array is not casting the local array to the proper type

**Comment by coquelin77** [comment]
this comes from that they data type are still floats but the torch tensor is a DoubleTensor not a float tensor

**Comment by Markus-Goetz** [comment]
I am confused. The above example seems to be right. float64 is a double precision floating point number. What seems to be the issue here?

**Comment by coquelin77** [comment]
sorry, i was not paying enough attention
