### ISSUE TITLE
Offset and strides of slices/views are not correctly used in MPI

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#301]
Consider the following example:

```
x = ht.ones((6,1), split=0) 
y = ht.ones((6,1))
print(ht.mul(x, y[1]))
```
Will result in an error, while 

```
print(ht.mu(x,y[1].copy()))
```
works fine. Working hypothesis of this bug is that the offsets and strides of the slice/view (a reference to the initial base buffer) are not correctly read out in the `ht.core.communication.as_buffer()` method.

**Comment by coquelin77** [comment]
i am unable to reproduce this locally. can you add an error message?

**Comment by Cdebus** [comment]
I can have a look at it when I'm reworking the binary operations

**Comment by ClaudiaComito** [comment]
I can't reproduce it either, anyway, FWIW, torch.clone() doesn't preserve the memory format, see https://github.com/pytorch/pytorch/pull/30089 . The original memory-layout / stride information is lost in the current implementation of ht.copy().

**Comment by mtar** [comment]
Bump
What's the status?

**Comment by coquelin77** [comment]
im still unable to reproduce this. unless someone objects i will close it tomorrow

**Comment by coquelin77** [comment]
perhaps this was fixed with the slicing

**Comment by lenablind** [comment]
> im still unable to reproduce this. unless someone objects i will close it tomorrow

I guess this is a silent approval :D May you/someone close the issue? @coquelin77 @ClaudiaComito @Markus-Goetz
