### ISSUE TITLE
improvements on matmul: ND array support (numdim > 2)

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#306]

**Comment by coquelin77** [comment]
Separate improvement: testing of optimal block size/shape on large matrices

**Comment by coquelin77** [comment]
improve multi-threading in matmul using https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html

**Comment by ClaudiaComito** [comment]
@coquelin77 ping...

**Comment by ClaudiaComito** [comment]
There is a newer version of this issue with more context, see #1104 . I'll close this one.
