### ISSUE TITLE
Binary operators should return NotImplemented

### ISSUE THREAD

**Issue by bhagemeier** [helmholtz-analytics/heat#311]
Acc. to https://docs.python.org/3/library/constants.html#NotImplemented , binary special methods should return NotImplemented rather than raising NotIpmlementedError (cf. https://docs.python.org/3/library/constants.html#NotImplemented and corresponding note).

HeAT currently raises NotImplementedError in those cases.

**Comment by AsRaNi1** [comment]
HI! I would like to work on this issue!

**Comment by AsRaNi1** [comment]
Respected Sir,

Surely, the feedback is taken and i would look for any other issues to work on. If in fact in the bi-weekly meeting this does come out as an issue, i would be more than glad to work on it.

Best Regards,
Arnav

**Comment by ClaudiaComito** [comment]
This issue is indeed still open. Related to #1184 

---
Reviewed within #1109
