### ISSUE TITLE
Document installation options

### ISSUE THREAD

**Issue by bhagemeier** [helmholtz-analytics/heat#335]
It has been brought to our attention that users are struggling to install HeAT. There are several options for this, depending on whether one wants to install an official release or a development version. This information should be available in the documentation as well as the README.md file.

**Comment by Markus-Goetz** [comment]
I am not sure what that means. What are the issues? Are they unable to install optional features? Is the installation failing entirely?

**Comment by bhagemeier** [comment]
I think this is related to someone once asking for a "requirements.txt", which would actually be the wrong way to install dependencies. However, the section in the README may not be quite sufficient. I have some local changes that should cover a bit more of what is required here, in particular the optional requirements. Will create a PR from them. I've also updated the other documentation accordingly.
