### ISSUE TITLE
implement symmetric eigenvalue solver

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#336]
PyTorch uses LAPACK on the backend, we cannot simply use ScaLAPACK for a variety of reasons. However the ideas of ScaLAPACK can be used in conjunction with the LAPACK already implemented in PyTorch.

For this issues a few other implementation are required. these are listed below:
- [ ] tridiagonalize (likely with a block Householder scheme)
- [x] determinant (#337 )
- [x] matrix inverse (#338 )
- [ ] solver for the secular equation

Resources:
http://www.cs.utexas.edu/~inderjit/public_papers/scalapack_sc96.pdf
https://wwwmayr.in.tum.de/konferenzen/Jass09/courses/2/Kleine_Albers_paper.pdf
http://people.inf.ethz.ch/arbenz/ewp/Lnotes/chapters5-6.pdf
https://www2.eecs.berkeley.edu/Pubs/TechRpts/1994/CSD-94-799.pdf
https://www2.eecs.berkeley.edu/Pubs/TechRpts/1994/6315.html

**Comment by ClaudiaComito** [comment]
@mrfh92 you're the best person to update this. If the two open items are dealt with in separate issues, we can close this one.

---
Reviewed within #1109

**Comment by mrfh92** [comment]
From my point of view, the most feasible way for implementing a symmetric eigenvalue decomposition is a different one, namely the one proposed in https://www.math.ucdavis.edu/~freund/zolosirev.pdf based on Zolotarev Polar Decomposition
