### ISSUE TITLE
Rework MPI communication Wrappers

### ISSUE THREAD

**Issue by Cdebus** [helmholtz-analytics/heat#341]
**Related**
Related to Issue #233 : Wrong sorting in dndarray resplit was due to errorous allgatherv

**Feature functionality**
Refactor MPI global functions: allgather*, alltoall*, scatter*, gather*.
So far algorithmic of all these functions is bundled in _scatter_like. However, some assumptions do not hold for all functions. Thus, each group gets own generic wrapper

**Additional context**
Also implement testing functions accordingly (to see if elements are sorted correctly)

**Comment by ClaudiaComito** [comment]
What's the status here @Markus-Goetz ?

**Comment by Markus-Goetz** [comment]
Still pending, this issue also requires to account for non-contiguous striding of the input tensors, e.g. if it is a view, to read out the correct elements from the buffers.

**Comment by ClaudiaComito** [comment]
@Markus-Goetz 

> 

Is that right? @Markus-Goetz maybe I misunderstand the original issue. We've had `__allgather_like`, `__alltoall_like`, `__broadcast_like` for a very long time.

**Comment by mrfh92** [comment]
Resolved by merging of #1204
