### ISSUE TITLE
bug: outdated type calles in some tests

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#356]
**Description**
A clear and concise description of the bug and the associated functionality.

**To Reproduce**
1. Which module/class/function is affected? - unknown, must test
2. What are the circumstances under which the bug appears? - gpu testing
3. What is the exact error-message/errorous behavious?
```# exponential of float32
float32_tensor = ht.arange(start, end, step, dtype=ht.float32)
float32_floor = float32_tensor.floor()
self.assertIsInstance(float32_floor, ht.DNDarray)
self.assertEqual(float32_floor.dtype, ht.float32)
self.assertEqual(float32_floor.dtype, ht.float32)
> self.assertTrue(float32_floor._DNDarray__array.allclose(comparison.type(torch.float32)))
E AssertionError: False is not true
```

**Expected behavior**
Tests should pass without errors on GPUs

**Version Info**
 Which version are you using?  - must current master as of 6.08.2019

**Additional comments**
may be packaged with other bug fixes

**Comment by mtar** [comment]
Does this issue still exist?

**Comment by ClaudiaComito** [comment]
This seems to have been addressed 😅.  Closing.
