### ISSUE TITLE
Unit test errors with newest pytorch

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#358]
**Description**
The unit tests do not pass when using the newest pytorch.

**To Reproduce**
1. Which module/class/function is affected?
Unit tests; canonical_heat_type
2. What are the circumstances under which the bug appears? 
Using pytorch 1.2.0
3. What is the exact error-message/errorous behavious?
TypeError: data type torch.bool is not understood
KeyError: torch.bool

**Expected behavior**
Passing all Unit tests

**Comment by Markus-Goetz** [comment]
torch.bool did also not exist in torch 1.0 and 1.1. I am a bit puzzled by this issue

**Comment by coquelin77** [comment]
i think its a new addition. im updating the tests now. i have this in the assorted bug fixes branch

**Comment by coquelin77** [comment]
i have solved this in the mentioned branch. however i believe that the changes will force us to require torch 1.2.0. @Markus-Goetz does the docker need to be updated or will this happen automatically?

**Comment by mtar** [comment]
[Here](https://github.com/pytorch/pytorch/releases/tag/v1.2.0) is a list of changes in 1.2.0 if you're still interested.
Will it affect other parts as well?

**Comment by coquelin77** [comment]
I dont see that it will break many other things. there might be some minor changes here and there. i have the PR up already which includes the changes necessary.
