### ISSUE TITLE
Refactor unittests to use ht.random calls

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#378]
**Feature functionality**
Since ht.random is now in existence. A couple of unittests needs to be rewritten to be using the distributed random tensors instead of torch random tensors or torch + ht.array calls. It is also meaningful to get rid of the torch seeding and instead switch over to ht.random.seed

**Comment by ClaudiaComito** [comment]
Still plenty of torch random calls in our tests, in case somebody wants to tackle this.

**Comment by ClaudiaComito** [comment]
I'm going to close this because too low priority.

---
Reviewed within #1109
