### ISSUE TITLE
Enforce PEP-8

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#380]
**Feature functionality**
Several documentation and source code pieces are not PEP-8 conform (e.g. overlong lines, line breaks etc.). Enforce PEP-8 conformity by running a linter on PRs, reformat the existing code and make exceptions where meaningful.

Initial assignee may reassign

**Comment by Markus-Goetz** [comment]
Perhaps this https://github.com/psf/black

**Comment by bhagemeier** [comment]
Thanks for the hint. I had been looking at autopep8, but that does not "fix" E501 (line too long). I give Black a try.

**Comment by bhagemeier** [comment]
Apart from the local setup of a pre-commit hook, I added the same to our CI. That way, even if a developer has not setup his or her local environment properly, we'll catch style violations and other problems. After all, flake8 does more than just style checking.
