### ISSUE TITLE
Introduce warnings filter

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#382]
**Feature functionality**
Currently, some functions, like resplit() issue a warning regarding potentially large data copies. This issue is two-fold:

1. Issue a warning only, if the respective operands are actually large (find a sensible value, e.g. everything larger than 1 GB?, 10 GB?)
2. Introduce a top-level filter that allows to filter these warnings

**Comment by TheSlimvReal** [comment]
Should the user be able to filter for special kinds of warnings like `DeprecationWarning, ResourceWarning, ...` or is it sufficient to give him the ability to turn of all warnings.

I'm wondering if the warnings module of python already supports all of our needs and we only need to agree on some guidelines for creating warning messages.

Maybe the warning for large communication of data could also be moved to the communication interface and be applied to all communication calls. E.g. calling broadcast with a huge amount of source data would always issue a warning.

**Comment by Markus-Goetz** [comment]
The warnings module generally should support these needs. 

Personally, I think warnings should be issued at all places necessary, but simply not displayed regularly. Instead, these warnings should only be issued if heat/python is executed in a verbose or debugging mode of some sorts (can we meaningfully recycle the -v flag of the Python interpreter?)

Generally, I like the idea of moving warning regarding large data sizes down into the communication layer. Only issue is deciding what large is. Highly depends on the execution environment and I do not want to start bothering with any probing or benchmarking.

**Comment by TheSlimvReal** [comment]
Pythons documentation about flags says:

>  __-O__: Remove assert statements and any code conditional on the value of \_\_debug\_\_.

Which would mean to me that as long as the `-O`-Flag is not provided python is considered to run in the debug mode.
The regular case you are referring to in issue #381 is the case where unittests are run. There I would actually like to get warnings displayed because I should be aware of them.

For the production case (`-O`) flag is see the point of disabling the warnings by default and provide a option to toggle it.

**Comment by TheSlimvReal** [comment]
I looked into it a little bit more. If we want to keep using python's warnings module, there is an easy command line option:

> python some_file.py -Wignore

or for the tests

> pytest some_test.py -Wignore

this will not display any of the warnings thrown inside.
The other way round where you don't display warnings on default is more difficult. You would either have to create a separate warnings module which handels the logic or manage the filters in every module where a warnings are eventually submitted.

**Comment by ClaudiaComito** [comment]
Closing this for now.

---
Reviewed within #1109
