### ISSUE TITLE
Implement sparse matrices 

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#384]
**Feature functionality**
Design and implement a distributed sparse DNDarray class. Come up with one or more reasonable storage formats (e.g. COO, CRS, CSC, ...)

**Additional context**
PyTorch implements COO only at the moment with a very restricted operation set.

Interface design might be inspired by Armadillo and/or SciPy.sprarse

**Comment by Markus-Goetz** [comment]
Here is a great paper summarizing formats and operations on sparse tensors. I would go with a COO format first where the set of entries is roughly evenly distributed 

http://groups.csail.mit.edu/commit/papers/2016/parker-thesis.pdf

**Comment by ClaudiaComito** [comment]
CSR addressed in #1028 , thanks @Mystic-Slice

**Comment by ClaudiaComito** [comment]
the `ht.sparse` module has been implemented by @Mystic-Slice and released with v1.3.0. For the time being it supports distributed CSR matrices and element-wise operations. More work needed.

Related issues: #1039 #1040 #1046 #1043 #1044 

I'll close this issue for now.
---
Reviewed within #1109
