### ISSUE TITLE
Implement KMeans.predict()

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#389]
**Feature functionality**

Implement the method KMeans(k).predict(X) that, similar to the sklearn equivalent, will "Predict the closest cluster each sample in X belongs to."

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

**Comment by ClaudiaComito** [comment]
@Cdebus there you go.

**Comment by Markus-Goetz** [comment]
Isnt that a duplicate of #87 ?
