### ISSUE TITLE
balance_() destroys order

### ISSUE THREAD

**Issue by TheSlimvReal** [helmholtz-analytics/heat#413]
**Description**
Using balance with more than 4 processes results in a wrong balanced order

**To Reproduce**
Run the following script with 5 processes.
```
rank = ht.MPI_WORLD.rank
if rank in [0, 1]:
    arr = torch.empty([0], dtype=torch.int64)
elif rank == 2:
     arr = torch.tensor([0, 1])
elif rank == 3:
      arr = torch.tensor([2, 3, 4, 5])
elif rank == 4:
      arr = torch.tensor([6, 7, 8, 9])
a = ht.array(arr, is_split=0)
a.balance_()
print(a)
```
> 0: [2, 3] 1:[4, 5] 2: [0, 1] 3: [6, 7] 4: [8, 9]

1. Which module/class/function is affected?
The `balance_()` function
2. What are the circumstances under which the bug appears?
More than 4 processes involved
3. What is the exact error-message/errorous behavious?
Wrong order.

**Expected behavior**
The order of the array should be kepts

**Version Info**
master

**Comment by coquelin77** [comment]
this works properly if you add more data. this is an edge case for when there is only small amounts of data transferred. for example the code below runs without error:

```python
rank = ht.MPI_WORLD.rank
if rank in [0, 1]:
    arr = torch.empty([0], dtype=torch.int64)
elif rank == 2:
    arr = torch.tensor([0, 1])
elif rank == 3:
    arr = torch.tensor([2, 3, 4, 5])
elif rank == 4:
    arr = torch.tensor([6, 7, 8, 9, 10, 11, 12])
a = ht.array(arr, is_split=0)
a.balance_()
print(a)
```
ill look into a quick fix but some help would be appreciated. it is likely in the sending keeping slices
