### ISSUE TITLE
balance_() creates wrong order on 7 processes

### ISSUE THREAD

**Issue by TheSlimvReal** [helmholtz-analytics/heat#417]
**Description**
Using `balance_()` with n=7 processes on a small array results in a wrong order in some cases.

**To Reproduce**
```
rank = ht.MPI_WORLD.
if rank in [0, 1]:
  arr = torch.empty([0], dtype=torch.int64)
elif rank == 2:
  arr = torch.tensor([0, 1])
elif rank == 3:
  arr = torch.tensor([2, 3, 4])
elif rank == 4:
  arr = torch.tensor([5, 6, 7])
elif rank == 5:
  arr = torch.tensor([8, 9, 10])
elif rank == 6:
  arr = torch.tensor([11, 12, 13])
a = ht.array(arr, is_split=0)
a.balance_()
print('rank', rank, 'res', a)
```

This results in the wird result.
rank 0: [0, 1], should be [0, 1]
rank 1: [2, 3], should be [2, 3]
rank 2: [5, 6], should be [4, 5]
rank 3: [4, 7], should be [6, 7]
rank 4: [8, 9], should be [8 ,9]
rank 5: [10, 11], should be [10, 11]
rank 6: [12, 13], should be [12, 13]

Somehow the values in the middle are not correctly balanced.

**Comment by coquelin77** [comment]
solved in pr #418
