### ISSUE TITLE
Update split-axis after mean/var along axis

### ISSUE THREAD

**Issue by ben-bou** [helmholtz-analytics/heat#421]
**Description**
mean(axis=ax) and var(axis=ax) change the shape and thereby possibly change the split-axis. If that happens, the _DNDarray__split attribute is not updated to the new split-axis. 

**To Reproduce**
1. Which module/class/function is affected?
.mean(axis=ax) and .var(axis=ax)
2. What are the circumstances under which the bug appears?
If calculating the mean/variance along one axis changes the split-axis.
This is the case if split_axis >= ax 
3. What is the exact error-message/errorous behavious?
The _DNDarray__split attribute is not updated to the new split-axis. 

**Expected behavior**
If a 3D-Tensor with dimensions (x,y,z) is split on the y-dimension (split-axis=1) and the mean along the x-dimension is calculated, the result is of dimension (y,z). Thereby, the split-axis should now be 0. 

**Illustrative**
If applicable, add screenshots or minimal examples to help explain your problem.
[variance_wrong_split.pdf](https://github.com/helmholtz-analytics/heat/files/3901027/variance_wrong_split.pdf)

**Version Info**
Version: 0.1.0
Branch: master
Commit: e637fc7

**Additional comments**

**Example Code**
```
import heat as ht
#Generate data
tensor = ht.ones((1,2,2), split=None)
tensor[:,1,:] = 2
tensor = tensor.resplit_(1)

#Save data
ht.save_netcdf(tensor, 'original-data.nc', 'data')
#Save mean
mean = tensor.mean(axis=0)
ht.save_netcdf(mean, 'wrong-split.nc', 'mean')
#Manually set split-axis 
mean._DNDarray__split = 0
ht.save_netcdf(mean, 'correct-split.nc', 'mean')
```
EDIT: use markdown for code

**Comment by coquelin77** [comment]
Are you seeing changes in the results?

The split axis does not need to be fixed to one axis. this is something that only has to do with how the data is distributed between on the processes. Functions which result in a dimensional reduction, such as mean and variance, can change the split axis however these changes should not change the results, nor does it reorient the data. 

So in your example, the split axis is 1 to begin with (the y dimension) but after the mean operation the split axis is still equal to 1. However, now this is the z dimension. These split semantics can be tricky but the hope is that you don't need to worry about them. 

Also, setting the split axis with `mean._DNDarray__split = 0` is typically not a good idea as this only sets the value of the split axis but does not change the distribution of the data on the nodes.

PS to put code in these messages (or on Mattermost, Rocketchat, Slack or anywhere else that supports Markdown) surround your text with the ` character for inline code and ``` for blocks

**Comment by ben-bou** [comment]
Thank you!

> Functions which result in a dimensional reduction, such as mean and variance, can change the split axis however these changes should not change the results, nor does it reorient the data.
So in your example, the split axis is 1 to begin with (the y dimension) but after the mean operation the split axis is still equal to 1. However, now this is the z dimension. 

So the data is not reoriented, i.e. still distributed along the y-dimension, but the split-axis is set to the z-dimension, right?
Then e.g. the Communications.chunk() would return the chunks as if the data was distributed at the z-dimension. This then leads the save_netcdf() method to put the data in the wrong slices.

**Comment by coquelin77** [comment]
The split axis is not set in the traditional sense. Because the data is distributed, the dimensional reduction will reduce the number or dimensions but it will not maintain the same split axis logically. Typically the split axis is chosen to be maintained numerically if possible. 

The data is not reoriented, however during a dimensional reduction the shape of the data changes. It is because of this that the split axis also changes. This shouldnt effect the saving procedure, the data should be the same before the save and after you load it. The splitting is only where the data is divided between processes. 

For example:
```python
>>> x = ht.array(torch.arange(8, dtype=float).reshape((2, 2, 2)), split=1)
[0] tensor([[[0., 1.]],
[0] 
[0]         [[4., 5.]]], dtype=torch.float64)
[1] tensor([[[2., 3.]],
[1] 
[1]         [[6., 7.]]], dtype=torch.float64)
>>> print(ht.mean(x, axis=0))
[0] tensor([[2., 3.]], dtype=torch.float64)
[1] tensor([[4., 5.]], dtype=torch.float64)
>>> print(ht.mean(x, axis=0).shape, ht.mean(x, axis=0).lshape)
[0] (2, 2), (2, 1)
[1] (2, 2), (2, 1)
```

This operation does not change the orientation of the data but it does change the logical split axis from the y to the z axis. However the numerical value of the split axis remains 1.

**Comment by ben-bou** [comment]
```
[0]:	 mean: 
 tensor([[2., 3.]], dtype=torch.float64) 	split: 1

[1]:	 mean: 
 tensor([[4., 5.]], dtype=torch.float64) 	split: 1

[0]:	 load: 
 tensor([[2.],
        [3.]]) 	split: 1

[1]:	 load: 
 tensor([[4.],
        [5.]]) 	split: 1
```
error appears to be in the saving of the data to a file
