### ISSUE TITLE
Concatenate changes comm

### ISSUE THREAD

**Issue by TheSlimvReal** [helmholtz-analytics/heat#422]
**Description**
When using the `concatenate` function, the comm of the result is eventually a different one than the comm of the input arrays. The comm will be changed when it's not `ht.MPI_WORLD` but another custom one. The `concatenate` function does not specify a comm internally and thus the `ht.MPI_WORLD` comm will be used for the result.

**To Reproduce**
```
a = ht.arange(23, split=0, comm=MPICommunication())
b = ht.zeros(2, comm=a.comm)
print('a', a.comm)
print('b', b.comm)

c = ht.concatenate((b, a))

print('c', c.comm)
```
1. Which module/class/function is affected?
`concatenate` in `manipualtions`
2. What are the circumstances under which the bug appears?
setting a custom communicator
3. What is the exact error-message/errorous behavious?
No error message, just unexpected behaviour.

**Expected behavior**
A comm of the input arrays should be used

**Additional comments**
I am not quite sure what the expected behaviour here would be.

**Comment by coquelin77** [comment]
there are 2 options for this.
1. we leave it as it is. in this case the returned DNDarray has its own communicator and it is assumed that we are working on the whole world. 
2. we use the communicator from one of the inputs

I am partial to the first. i think that a new array should have its own communicator. however I have just noticed a different bug in cat -> the inputs are unbalanced in the process of the code but they are not re-balanced at the end of the functoin

**Comment by Markus-Goetz** [comment]
comms of a and b should be consistent. So it will be the comm of either one of the operators
