### ISSUE TITLE
Set up GitHub Actions

### ISSUE THREAD

**Issue by TheSlimvReal** [helmholtz-analytics/heat#424]
**Feature functionality**
GitHub introduced the GitHub Actions.
This is a CI/CD pipeline similar to the one GitLab already provides.
The benefit is that each build can be split into smaller more readable separated workflow units. 
Added to that, it's also possible to use self-hosted runners. This can be used to run our tests on a private machine with GPU support.

For more information check out the feature description [here](https://github.com/features/actions).

Tasks:

- [ ] Move current build process to GitHub actions
- [ ] Split build process into smaller units that can run in parallel
- [ ] Create deploy workflow for publishing the library on PyPi
- [x] Set up a self-hosted runner with GPU (HDF machine in Jülich)
- [x] Create test stage that also tests on the GPU

**Comment by TheSlimvReal** [comment]
About the self-hosted runners. GitHub offers an [easy way](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/adding-self-hosted-runners) to setup and add an server. All that needs to be done is to run an executable on the machine and add it to GitHub. However GitHub also mentions the security risks. Because we are using a public repository theoretically everybody can modify this workflow with malicious code and create a pull request which would execute the code. 
One way to prevent this is to only run the workflow on the master, so only approved changes are run. The problem there is that the workflow file is also available to everybody and therefore a workflow could be modified to execute code on the self-hosted runner even on a fork.
At the moment I don't see an easy solution to prevent this security problem.

**Comment by aktech** [comment]
Hi @TheSlimvReal I am the creator of Cirun.io, "tests on the GPU" caught my eye.

FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/

It is used in multiple open source projects needing GPU support like the following:

- https://github.com/pystatgen/sgkit/
- https://github.com/qutip/qutip-cupy

It is fairly simple to setup, all you need is a cloud account (AWS or GCP) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.

Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)

**Comment by ClaudiaComito** [comment]
@mtar what do you think, can we close this issue? Break it up in smaller parts? Some things have been implemented, others I'm not sure we still need/want them.
