### ISSUE TITLE
Automatic deployment on PyPI

### ISSUE THREAD

**Issue by bhagemeier** [helmholtz-analytics/heat#47]
This should be done from successful Travis CI build. Possibly only tagged versions. See https://docs.travis-ci.com/user/deployment/pypi/ for details.

**Comment by rainman110** [comment]
I was just about creating a new issue to this topic.

The latest HeAT package on PyPI is 0.1.0. The latest HeAT tag is currently 0.5.0. It seems, that the deployment on tag creation / release is not working properly.

**Comment by bhagemeier** [comment]
You're right. This may be related to the fact that Travis wasn't working properly for us for a while. Since it has been working again, we may not have created another tag. I can manually make the 0.5.0 release if needed.

**Comment by rainman110** [comment]
@bhagemeier  That would be nice! We have some collaboration in the DLR, who want to try out HeAT.

Installing the latest (0.5.0) version via pip is probably the easiest way to do so.

**Comment by bhagemeier** [comment]
Checked again. The latest git tag IS 0.1.0. That's also the latest version mentioned in heat/core/version.py, which is from where I take the release version. This needs to be updated. If everyone agrees that we should cut a release like this, then we can do it. I do know that @TheSlimvReal is working on a replacement mechanism to create automatic releases.

**Comment by rainman110** [comment]
Oh yes.. you are right. I was mixing it up with the 0.0.5 tag.

**Comment by rainman110** [comment]
Sorry for the noise!

**Comment by Markus-Goetz** [comment]
We should make a new release though. Have not done so in a while an there big changes and bug fixes. Maybe a 0.2.0 is on order

**Comment by bhagemeier** [comment]
Yep, I've taken the discussion to our chat. @coquelin77 had some feedback and wants to merge a couple of PRs before releasing. But if you agree, we'll get it out still this week.
