### ISSUE TITLE
Unsplit matrix multiplication changes split of first matrix argument

### ISSUE THREAD

**Issue by lehr-fa** [helmholtz-analytics/heat#472]
**Description**

The split of the first argument (X in the following example) gets changed from None to 0 during matrix multiplation. Example:

**To Reproduce**

```python
X = ht.zeros((200, 9), split=None)
A = ht.zeros((9, 10), split=None)
y = ht.matmul(X,A)
print(X.split)
```

```
 >> 0
```

1. Which module/class/function is affected: ```ht.linalg.matmul```
2. What are the circumstances under which the bug appears: Allways
3. What is the exact error-message/errorous behavious: The split changes from None to 0.

**Expected behavior**
 The split axis of the input args should be unchanged. In this case, X.split should be None

**Version Info**
HeAT Master

**Comment by lehr-fa** [comment]
@Cdebus In line https://github.com/helmholtz-analytics/heat/blob/f3eca8c518d26cdc7ae2ee88e2a785fcece959db/heat/core/linalg.py#L154

the tensor is resplit. Why is this necessary here? Both tensors are unsplit und could be simple multiplied. IMHO, no MPI is necessary at all for this particular case.

Another issue here could be, that the resplit really changes the input and not only a temporary variable.

**Comment by coquelin77** [comment]
Firstly, thank you for the issue! the rational here was to divide the computational load between the processes. 

The split is done assuming that the data size is large enough to see a benefit from parallelization. It does not do this on a temporary variable as that would require copying the memory which can be computationally expensive. However, this does raise a good point and an optional argument could be added to `matmul` to make this behavior optional. 

If you are experiencing any other problems please let us know!

**Comment by rainman110** [comment]
IMHO, resplitting should only be done for matrices that are "large enough", as a resplitting introduces additional overhead. Therefore, it is probably a good idea to check for a certain minimum size before resplitting.
