### ISSUE TITLE
implement a collect method 

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#480]
A user frindly method in order to collect a distributed tensor to one rank.
A special case of the redistribute_ method

**Comment by coquelin77** [comment]
cant this be done with `resplit(None)`?

**Comment by krajsek** [comment]
resplit(None) copies (at least in my understanding) data to all ranks,  which could be very expensive. In some cases you may want to do some  distributed computing and then process the data locally on one rank.

**Comment by ClaudiaComito** [comment]
This is still open and still a good idea. 

---
Reviewed within #1109
