### ISSUE TITLE
test_gaussiannb fails when distributed on 7 processes

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#490]
**Description**
Testing gets stuck, possibly nodes being left without data (iris test dataset is quite small).

**To Reproduce**

on branch features/340-GaussianNB
mpirun -n 7 python -m unittest

**Expected behavior**
Tests should not get stuck even if nodes are left without data

**Comment by mtar** [comment]
Which branch do you use?

**Comment by ClaudiaComito** [comment]
> Which branch do you use?

Sorry, branch is features/340-GaussianNB, I'll add this info in the general description.
