### ISSUE TITLE
data type homogenization

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#491]
**Description**
dndarray constructors differs in datatype, e.g. 
ht.random.randn(1) ->  dtype=torch.float64
ht.ones(1)  -> dtype=torch.float32

**Expected behavior**
All constructors should (if possible) return the same data type by default. I recommend float32.

**Comment by Markus-Goetz** [comment]
Would recommend sticking to the numpy baseline. That means consistently float64/int64.

**Comment by krajsek** [comment]
This is reasonable for reasons of consistency with Numpy. On the other hand, float
 is sufficient for most ML algos, and memory on GPUs is still precious.

**Comment by Markus-Goetz** [comment]
What about integers? Shall we go with int32 as well or leave it at int64?

**Comment by krajsek** [comment]
Well, we try to keep as close as possble to the NumPy API, but we build on top of PyTorch. My feeling is therefore to stay as close as possible to PyTorch with respect to data types and PyTorch uses int64 as default value but float32 for floating poin numbers.
