### ISSUE TITLE
bug distributed array from scalar

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#492]
**Description**
factories.array does not support 0-dim tensors if split is not None.

**To Reproduce**
1. Which module/class/function is affected?
factories.array / stride_tricks.sanitize_axis
2. What are the circumstances under which the bug appears?
create splitted heat array from scalar
3. What is the exact error-message/erroneous behaviour?
```bash
Traceback (most recent call last):
  File "pt.py", line 4, in <module>
    a = ht.array(1, split=0)
  File "heat/core/factories.py", line 323, in array
    split = sanitize_axis(obj.shape, split)
  File "heat/core/stride_tricks.py", line 109, in sanitize_axis
    raise ValueError("axis {} is out of bounds for shape {}".format(axis, shape))
ValueError: axis 0 is out of bounds for shape torch.Size([])
Traceback (most recent call last):
  File "pt.py", line 4, in <module>
    a = ht.array(1, split=0)
  File "heat/core/factories.py", line 323, in array
    split = sanitize_axis(obj.shape, split)
  File "heat/core/stride_tricks.py", line 109, in sanitize_axis
    raise ValueError("axis {} is out of bounds for shape {}".format(axis, shape))
ValueError: axis 0 is out of bounds for shape torch.Size([])
```

**Expected behaviour**
Create 0-dim heat tensor

**Illustrative**
```
a = ht.array(1, split=0)
```
```
b = ht.array(torch.tensor(0), split=0)
```
**Version Info**
v0.3.0

**Additional comments**
This bug affects issue #490

**Comment by ClaudiaComito** [comment]
@mtar do you think this is causing #490? I don't see why the tests wouldn't fail with 2 processes already if this were the problem.

(why distribute a scalar would be my next question)

**Comment by mtar** [comment]
The bug happens more specifically in indexing.nonzero() lines 74-75 when lcl_nonzero has only one element:
```python
if a.numdims == 1:
    lcl_nonzero = lcl_nonzero.squeeze()
return factories.array(lcl_nonzero, is_split=is_split, device=a.device, comm=a.comm)
```
In this particular case, squeeze will return a 0-dim tensor and stuff happens.

On seven processes, you run into it (line 346).
