### ISSUE TITLE
documentation formatting

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#504]
There are formatting errors in the documentation on Read the Docs:

- ~[Introduction chapter](https://heat.readthedocs.io/en/latest/introduction.html) has no formatting at all~
- generated API [has](https://heat.readthedocs.io/en/latest/autoapi/heat/core/dndarray/index.html) [some](https://heat.readthedocs.io/en/latest/autoapi/heat/core/statistics/index.html#heat.core.statistics.cov) [problems](https://heat.readthedocs.io/en/latest/autoapi/heat/core/factories/index.html#heat.core.factories.array)

**Comment by mtar** [comment]
The logo is missing

**Comment by coquelin77** [comment]
@mtar work on this is ongoing where that should be fixed
