### ISSUE TITLE
Speeding up slicing

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#505]
Slicing is currently more than one magnitude slower than corresponding manuel operations, e.g.:

X = ht.array(torch.randn(10000,11), split=0)

X_j = X[:, 0] - > takes about 0.3 sec.

X_j = ht.array(X._DNDarray__array[:, j], split=0) -> takes about 0.02sec.

**Comment by Markus-Goetz** [comment]
Should be resolved by PR #594
