### ISSUE TITLE
implement split functions

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#510]
**Feature functionality**
A clear and concise description of what the feature should do exactly and any alternative solutions.

Provide split functions (split, hsplit, vsplit, dsplit, ...)

**Comment by coquelin77** [comment]
what do you mean split function? functions to resplit the dndarray?

**Comment by mtar** [comment]
No, really splitting it into two seperate tensors like in the numpy functions I mentioned.

**Comment by Cdebus** [comment]
I think in our context, 'splitting' might be a poor choice of words. To avoid confusion, we should find other naming, even if it deviates from the numpy API. Just my two cents

**Comment by lenablind** [comment]
> I think in our context, 'splitting' might be a poor choice of words. To avoid confusion, we should find other naming, even if it deviates from the numpy API. Just my two cents

I would agree. Any suggestions? @Cdebus @coquelin77 @mtar
