### ISSUE TITLE
Get rid of either the doc or docs folder

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#532]
Unify both folders into one

**Comment by bhagemeier** [comment]
Yes, I've seen this as a nuisance, too. However, the reason for creating a separate folder was probably that it should not interfere with the Sphinx doc sources. We could move the doc sources further down and put the PR template into the same folder. What do you think? @Cdebus  is currently working on the docs, so I would only want to do this once she has done her part.

**Comment by Markus-Goetz** [comment]
Seems like a good idea. I do not think that this will interfere with what @Cdebus is doing
