### ISSUE TITLE
Rework unittest to be more atomic

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#533]
Break down existing unittest cases into singular, more atomic test cases instead of multiple in a single method

**Comment by ClaudiaComito** [comment]
@Markus-Goetz can you implement this change just for one module, or even one function? Then we can take off from there

**Comment by mrfh92** [comment]
In principle a good and important idea, although maybe not our highest priority at the moment. 
Should rather become part of our README, to keep future unittests as atomic as possible. 

Reviewed within #1109

**Comment by ClaudiaComito** [comment]
I'm going to close this issue for now.
