### ISSUE TITLE
Introduce larray property

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#538]
**Feature functionality**
Introduce the larray property that allows access to the underlying torch tensor of a DNDarray.

**Additional context**
Replace the internal member access _DNDarray__array using the new property.
Add a big fat warning, that manipulating the local contents of a DNDarray needs to be done with care and might corrupt/invalidate the metadata in a DNDarray instance.

**Comment by lenablind** [comment]
@Markus-Goetz The only valid dtype for setting _DNDarray__array should therefore be a torch tensor, right?
