### ISSUE TITLE
Implement distributed topk()

### ISSUE THREAD

**Issue by Inzlinger** [helmholtz-analytics/heat#563]
https://pytorch.org/docs/stable/torch.html?highlight=topk#torch.topk
@Inzlinger

**Comment by ClaudiaComito** [comment]
We should call this argpartition(), correct?
https://numpy.org/doc/1.18/reference/generated/numpy.argpartition.html

Indeed it would be great to have this.

**Comment by Markus-Goetz** [comment]
This is actually slightly different from argpartition due to better suitability to GPUs. Even though it is not in numpy, you can find it in Torch. I would want to make a small exception here in favor of topk. What do you think @ClaudiaComito

**Comment by ClaudiaComito** [comment]
> This is actually slightly different from argpartition due to better suitability to GPUs. Even though it is not in numpy, you can find it in Torch. I would want to make a small exception here in favor of topk. What do you think @ClaudiaComito

I'm all for it @Markus-Goetz . They do slightly different things, I only thought of argsort() because that's what I would use to get a topk-type of functionality in numpy. Maybe we can have both eventually.

Better suited for GPUs in which sense?
