### ISSUE TITLE
get_halo behaviour if no data on process

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#568]
**Description**
Currently, `dndarray.get_halo` raises a ValueError if the size of the tensor along the split axis is smaller than the number of MPI ranks (i.e., empty tensors on some ranks).

Couldn't `get_halo` treat the last non-empty rank as the last rank, and leave the others alone (empty), but still return `array_with_halos` on the populated ranks? 

**To Reproduce**
See errors in test_statistics.test_percentile() here
https://travis-ci.com/github/helmholtz-analytics/heat/builds/166837904

where data.gshape was (6, 10, 10) on 7 nodes.

(I've currently changed the data size to (10, 10, 10) in order to be able to build the PR)

**Expected behavior**
Ideally the program shouldn't crash if  `x.gshape[x.split] < x.comm.size`

**Version Info**
Branch features/22-percentile

**Comment by lucaspataro** [comment]
Hi @ClaudiaComito,

sorry for my late reply. 
I agree with you, such a scenario should definitely be possible. I will have a look next week how this can be realised.
