### ISSUE TITLE
Type promotions in binary operations

### ISSUE THREAD

**Issue by d1saster** [helmholtz-analytics/heat#574]
Hi guys,
I am having an issue with the type promotions in the binary operations, which seem to be asymmetrical:
```
#!/usr/bin/env python
import heat as ht

a = ht.array([1.0, 2.0, -0.5])
b = ht.array([1.0, 2.0, -0.5],dtype=ht.float64)

# BUG: The following lines give float32, float64, float32, but should be float32, float64, float64
print(a.dtype, b.dtype, (a*b).dtype)
print(a.dtype, b.dtype, (a/b).dtype)

# These lines work as expected:
print(a.dtype, b.dtype, (b*a).dtype)
print(a.dtype, b.dtype, (b/a).dtype)

# This gives the correct result: float64
print(ht.promote_types(a.dtype,b.dtype))
```

From what I can tell the following lines are the problem, which are executed before `ht.promote_types` has a chance to select a type.
https://github.com/helmholtz-analytics/heat/blob/042d0a88b17283522ec94c2caf06be1d526f2550/heat/core/operations.py#L138-L139

There exists similar code a bit earlier in the file:
https://github.com/helmholtz-analytics/heat/blob/042d0a88b17283522ec94c2caf06be1d526f2550/heat/core/operations.py#L67-L68

Thx.

**Comment by coquelin77** [comment]
i believe that this is solved in PR #575
