### ISSUE TITLE
Documentation: automatically check correctness of documentation during CI

### ISSUE THREAD

**Issue by rainman110** [helmholtz-analytics/heat#588]
At the current stage, HeAT often has some API changes which also require a change of the documentation.

This is however often forgotten and we have no mechanism to be informed automatically, if the doc goes "out of sync".

Therefore, we should employ a tool that checks this automatically. 

The following tools seem to be applicable:
 - *Doctest*: a tool to test code snippets in docs, https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html
 - *pylint*: general static analyzer, also checks function args, arg types ...
 - *pydocstyle*: style checker of docstrings (do we really need style checks?), https://github.com/pycqa/pydocstyle

These tools can probably integrated with flake8.

**Comment by Markus-Goetz** [comment]
We are using black for PEP-8 compliance and not flake8.

Functions do not have type annotations yet and won’t have them for the foreseeable future because of Torch’s JIT type annotations inside comments.
