### ISSUE TITLE
Allow for lossy type promotion

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#597]
we are currently doing safe casting, i.e. precision preserving, meaning ``promote_type(int32, float32) -> float64`` as ``float32`` might be lossy in the conversion

_Issue created from a [Mattermost message](https://mattermost-haf.fz-juelich.de/_redirect/pl/c6oqcayx4pbx8qbk96ecx7onao) *by @Markus-Goetz*._

**Comment by ClaudiaComito** [comment]
*@ClaudiaComito attached a* [message](https://mattermost-haf.fz-juelich.de/_redirect/pl/88rm1hxkwbrnpqxzwhy8sima5w) *from @Markus-Goetz*

Since we are doing probabilistic/heuristic stuff often anyway, I would be fine with natural expectation over safe casting

**Comment by Markus-Goetz** [comment]
Daniel has implemented something like this already. We called it "intuitive" casting. The table is already in the master. If you can find more example of where we should relax the casting, based on the table, we can implement this fairly quickly

**Comment by coquelin77** [comment]
give me a second and i will push a branch to the master. im just updating the docstring

**Comment by Markus-Goetz** [comment]
Closed by #598
