### ISSUE TITLE
implement k-medoids

### ISSUE THREAD

**Issue by ArtVoro** [helmholtz-analytics/heat#599]
**Feature functionality**
Implement the medoid flavor of the k-means algorithm, i.e. the centroids need to be identical to a k-subset of the data points. Comes down to recalculating the distance matrix of the averaged centroids and the data points after each optimization iteration and selecting the closest one. 

**Additional context**
very similar to your existing kmeans implementation.

**Comment by Cdebus** [comment]
A basic implementation is done, that utelizes median calculations (with Manhattan distance) and snaps the centroids to the closest data point in each iteration (see PR  #634 ). Does that cover it for you, or do you need the actual partitioning around medoids (PAM) algorithm as proposed by Kaufman and Rousseeuw ?

**Comment by ArtVoro** [comment]
@Cdebus yes this covers it. thank you.

**Comment by Cdebus** [comment]
Brilliant, then I can close this. Let me know if there are any issues with this
