### ISSUE TITLE
Documentation - add 'Hello World' page

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#612]
**Feature functionality**
Add a page in the documentation showing a small 'Hello World' usage example.

**Comment by ClaudiaComito** [comment]
@Markus-Goetz this is covered by our [tutorial](https://github.com/helmholtz-analytics/heat/blob/main/scripts/tutorial.ipynb), correct?

**Comment by Markus-Goetz** [comment]
More or less, it would be good to make a copy of that in the documentation as well. Moreover, it would probably good to use the split tensor figure from the paper instead of the current one

**Comment by mrfh92** [comment]
Meanwhile we have "Getting Started" on our README and also "TL;DR: Quick Start" 

Therefore, closed within #1109
