### ISSUE TITLE
Modify  functions to use Parameter Type hints

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#630]
_Issue created from a [Mattermost message](https://mattermost-haf.fz-juelich.de/_redirect/pl/tbjfh4iq9bbqpyi1xcuoqeif4e) *by `@cdebus`*._

I have compiled a list for who will take care of which module (aka .py file). The task is simple: For the modules assigned to you, please modify the functions to use Parameter Type hints. Also, there are a few functions which are still completely missing docstrings. I have put them in square brackets behind the respective module, so if one of your modules has that, please complete the docstring for that function:

@Markus-Goetz  :  constants.py, devices.py, factories.py, kmeans.py, logical.py, base.py [class BaseEstimator], io.py[supports_hdf5, supports_netcdf], random.py [\__counter_sequence], memory.py, stride_tricks.py, trigonometrics.py
@cdebus : spectral.py, distance.py , solver.py, laplacian.py, communication.py
@coquelin77 :  linalg/basics.py [ \__mm_c_block_setter], qr.py, tiling. py [arr, lshape_map, tile_dimensions, get_tile_slices, get_tile_size, \__adjust_cols_sp1_m_ls_n, \__adjust_last_row_sp0_m_ge_n, \__adjust_lshape_sp0_1tile, \__def_end_row_inds_sp0_m_ge_n, \__last_tile_row_adjust_sp1], statistics.py [mpi_argmin, mpi_argmax]
@ClaudiaComito  : gaussianNB.py, exponential.py, indexing.py, manipulations.py [mpi_topk]
@krajsek : lasso.py, operations.py, arithmetics.py, dndarray.py [halo_prev, halo_next, gshape, lloc(does not match), \__repr\__]
@d1saster  : relational.py, rounding.py, types.py, matrixgallery.py

**ATTENTION**: All changes to the docstrings are to be made to the  504-docstring-formatting branch! That way,in the end we get one large Pullrequest from hell with all changes, that will be easier to merge than if I have to stitch together all the changes. I know that the branch is so far not building, there are still circular dependencies existing, but I am taking care of it.

Also, this branch contains now a "documentation_howto.rst": This is a textform version of the presentation I gave at the Dev Week. So for a manual on how to write the new docstrings, see : https://heat.readthedocs.io/en/504-docstring-formatting/documentation_howto.html

_Issue created from a [Mattermost message](https://mattermost-haf.fz-juelich.de/_redirect/pl/tbjfh4iq9bbqpyi1xcuoqeif4e) *by `@cdebus`*._

**Comment by ClaudiaComito** [comment]
Hi @Inzlinger , can you take over docstring and parameter type hints for mpi_topk ?

**Comment by Markus-Goetz** [comment]
Done

**Comment by ClaudiaComito** [comment]
Closed by #757
