### ISSUE TITLE
Bug in Reshape

### ISSUE THREAD

**Issue by Inzlinger** [helmholtz-analytics/heat#654]
**Description**
MPI.Exception : MPI_ERR_TRUNCATE on reshape.

**To Reproduce**
Run with n>1 threads:
```
import heat as ht

source_shape = (1600080, 17)
target_shape = (20001, 80, 17)

a = ht.zeros(source_shape, split=0)

print(a.lshape, a.gshape)
a = ht.reshape(a, target_shape)
print(a.lshape, a.gshape)

```

**Expected behavior**
Reshape to target shape.

**Version Info**
Heat on Branch Master, last commit 9b1f28bc9db00001085e26cb764b7de0714ffea1

**Additional comments**
Tried some different numbers for the shapes but did not find any meaningful pattern.

**Comment by mtar** [comment]
Does #684 fix the problem?
