### ISSUE TITLE
Indexing does not preserve the lshape of elements

### ISSUE THREAD

**Issue by Inzlinger** [helmholtz-analytics/heat#656]
**Description**
When using list slicing the local shape of MPI-Ranks that are left empty cause issues with other functions, as their shape is always (0,).

**To Reproduce**
Run with n>2:
```
import heat as ht

a = ht.array([[1,1],[2,2],[3,3]], split=0)
index = ht.array([0, 1], split=0)
b = a[index]
b.balance_()
print(b.lshape, b.gshape)
ht.spatial.cdist(a,b)
```

**Expected behavior**
Lshape consistent over all ranks, even when they are left empty.

**Version Info**
HeAT on branch master, f2ca0021cf8c9ecefaa0be384e7e83ade53bd663

**Comment by ClaudiaComito** [comment]
@Inzlinger thanks for reporting this and sorry it took so long to get back to you. If you can, check out [this branch](https://github.com/helmholtz-analytics/heat/tree/bug/754-getitem-indexing) - I hope we have a more consistent indexing there. Let me know how it goes.
