### ISSUE TITLE
downcasting parameters for Data parallel

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#663]
**Feature functionality**
downcast the parameters for MPI communications in DP neural networks

**Comment by ClaudiaComito** [comment]
Kowalski, status? :) @coquelin77

**Comment by mrfh92** [comment]
@coquelin77 is this stil relevant? - to be honest, I even do not understand whats the topic... 

(stil to be reviewed within #1109)

**Comment by ClaudiaComito** [comment]
Let's close this for now.
