### ISSUE TITLE
Reshape with unknown dimension (-1) is not supported

### ISSUE THREAD

**Issue by sebimarkgraf** [helmholtz-analytics/heat#696]
**Description**
Numpy and PyTorch both allow to set one axis to ``-1``.
In that case the axis is calculated from the remaining axis.

Here the documentation from torch:
> A single dimension may be -1, in which case it’s inferred from the remaining dimensions and the number of elements in input.

**To Reproduce**
Example is taken from the PyTorch documentation and adjusted to HeAT.
```python
import heat as ht

b = ht.array([[0, 1], [2, 3]])
print(ht.reshape(b, (-1,)))
```

**Expected behavior**
```[ 0,  1,  2,  3]``` 
But throws a validation error.

**Version Info**
0.5.0

**Additional comments**
I want to use this to flatten features on the different nodes. Is this on purpose to prevent weird scenarios with the splitted data?

**Comment by mtar** [comment]
reshape(-1) is equivalent to ravel() which is not implemented yet. However, you can use flatten() instead.

**Comment by Markus-Goetz** [comment]
Nevertheless this should be implemented

**Comment by coquelin77** [comment]
see #690 @mtar can you add the changes to reshape in the ravel branch if not already there?

**Comment by mtar** [comment]
Yes, I'm on it.

**Comment by sebimarkgraf** [comment]
@mtar  Thanks for the suggestion!
But I want to keep the first axis as is and just reshape all others. As far as I know, neither flatten nor ravel support this.
```python
a = ht.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a = ht.reshape(a, (a.shape[0], -1))
> a = [[1, 2, 3, 4], [5, 6, 7, 8]]
```
I am currently doing the necessary computations for the dimension myself.
Due to this being a common use  case, I filed the issue.

**Comment by mtar** [comment]
So you want one dimension of the new shape to be inferred, right?
