### ISSUE TITLE
Duplicate __reduce_op, "There can be only one"

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#72]
After the recent merging of max/min and sum implementations, we have tensor.__reduce_op and operations.__reduce_op.  I would like to converge on operations.__reduce_op as it fits the schema we are following with the local operations as well.

**Comment by ClaudiaComito** [comment]
@krajsek 
Hi Kai,

I've updated operations.__reduce_op, could you check if you're happy with it and if it works well with tensor.sum()? I see your tests are a lot more detailed than mine, so I expect you'll find inconsistencies that I haven't noticed. Thanks a lot!

**Comment by krajsek** [comment]
> 
> 
> @krajsek
> Hi Kai,
> 
> I've updated operations.__reduce_op, could you check if you're happy with it and if it works well with tensor.sum()? I see your tests are a lot more detailed than mine, so I expect you'll find inconsistencies that I haven't noticed. Thanks a lot!

Hi Claudia,

please open a pull request, then I can directly see your changes. I am on vacation this week -> do not expect immediate reply to requests.

**Comment by ClaudiaComito** [comment]
Ah yes sorry, pull request is out. 

Have fun!
