### ISSUE TITLE
Simplest example does not work with MPI

### ISSUE THREAD

**Issue by fschlimb** [helmholtz-analytics/heat#745]
Trying to run something as simple as 
```
import heat as ht
a1 = ht.zeros(10, split=0)
print(a1)
```
running this with 2 processes assigns the entire array to rank 0:
```
> mpirun -n 2 -prepend-rank python runme_heat.py
[1] a1:
[0] a1: DNDarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=ht.int32, device=cpu:0, split=0)
```

I am using Intel MPI (conda create -n idp -c intel python impi-devel).

Any idea?

**Comment by coquelin77** [comment]
please print `a1.lshape` to show the the local torch tensors. otherwise, the printing in HeAT will look similar to what is expected when using numpy or torch

**Comment by Markus-Goetz** [comment]
One more addition to @coquelin77 comment, DNDarrays, even when distributed, are only printed on rank 0 in order to keep output readable. If you are interested in the node local data portions, please try `a1.larray`

**Comment by fschlimb** [comment]
Ok, I see, thanks. This works as you describe.

"what is expected when using numpy" apparently is not clear as one could think. Personally, I would have expected that each rank behaves similar when it refers to the same 'global' array instance and its attributes. In particular as the tutorial makes this impression. It's definitely ok the way it is, it only could use some explanation in the tutorial, I guess.

Similarly, while I do understand the motivation for it, I'd argue that suppressing an explicit print statement is not a intuitively a good behavior.

**Comment by coquelin77** [comment]
There was a lot of internal debate about how to do the prints. the problem arises when the data size and process count increases. The intent of printing on a single process was to simplify the output for users; specifically, those which are unfamiliar with parallel programming. 

The goal of HeAT is to do the parallel computing transparently, so the global array is distributed and the operations on it are done from a global perspective. In other words, each rank does something similar to the others but the results are combines on the fly to produce the desired results. Is this what you're referring to?

As for the explicit printing, perhaps a switch can be added to toggle between the print behaviors. It might be useful for learning and debug purposes.

**Comment by fschlimb** [comment]
@coquelin77 I can imagine the discussion has been lively :) I agree that a switch to enable/disable single-rank printing would be very helpful.

Yes, I was hoping a DNDArray would be a 'global' entity, all its standard numpy-attributes would refer to the whole array, not a local part. Only when explicitly asking for local attributes (like lshape) the parallel and distributed nature of the object would become apparent. It's clear of course that under the covers different ranks would perform different things.

I am evaluating HEAT because I am actually working on an implementation of distributed numpy as well. A lot of the thinking and goals seem to be alike here and there. Maybe there is a way to collaborate.

**Comment by coquelin77** [comment]
yes that is exactly what we are going for. 

we would definitely be interested in collaborating. 

lets discuss a time and place to meet via email. My email address is daniel.coquelin@kit.edu

**Comment by fschlimb** [comment]
Excellent. I'll get in contact with you.

I close this since it's not really an issue anymore.

Thanks for your help.
