### ISSUE TITLE
Document and make relational operators API-complete

### ISSUE THREAD

**Issue by rainman110** [helmholtz-analytics/heat#8]

**Comment by bhagemeier** [comment]
Generally available, but requires testing and documentation.

**Comment by Cdebus** [comment]
A short inquiry on the part "make relational operators more API complete": As I understand it, tensor operators (relational and binary operations, e.g. add, pow, le, etc) are already implemented on the internal class level (in tensor.py) and only need a little documentation, but still need to be implemented as heat functions on module level (e.g. ht.add(tensor1, tensor2)), similar to numpy functions? Should this then be put in operations.py? Or am I getting this completely wrong?

**Comment by Markus-Goetz** [comment]
Your are almost correct about everything. The implementations themselves should also be moved to operations.py and the methods should forward to these calls, see for example clip() in tensor.py and operations.py.

Other than that, documentation and tests are needed. There is currently a shortcoming in the implementation. It is NOT possible to perform binary operations on tensors with different splits, e.g. split=0 and split=1. This requires to redistribute the content of at least one of the arrays. I am working on the MPI layer, see issue #9

**Comment by Cdebus** [comment]
For completeness: as of now, these operations are class methods to the tensor class. Should this stay (and the operations in operations.py only tunnel to the tensor.py implementations), or should the basic implementation of the operations (i.e. __binary_op) move to operations.py (as functions which take two arguments) (and methods in tensor.py only tunnel implementations from operations.py, as done with clip())?

**Comment by Markus-Goetz** [comment]
The tensor methods need to stay and tunnel to the implementation in operations.py. __bin_op needs to be moved to operations.py as well. All the implementations in operations.py will take two arguments. E.g.:

```
class Tensor
    ...
    def __add__(self, other):
        return operations.add(self, other)
```
and in operations.py

```
def add(a, b):
    return __bin_op(a, b, ops.plus)

def __bin_op(...)
    ...
```
