### ISSUE TITLE
numpy.loadtxt vs heat.load_csv

### ISSUE THREAD

**Issue by fschlimb** [helmholtz-analytics/heat#814]
**Description**
load_csv is not from numpy API but behaves differently than naive use of numpy.loadtxt.

**To Reproduce**
```
import numpy as np
import heat as ht

a = np.zeros(8)
np.savetxt("a.csv", a, delimiter=',')

a1 = np.loadtxt("a.csv", delimiter=',')  # fix a: ndmin=2
a2 = ht.load_csv("a.csv")                # fix b: .squeeze()

assert a1.shape == a2.shape, f"Expected shape {a1.shape} but got shape {a2.shape}"
print(f"ok: {a1.shape}")
```

**Expected behavior**
Both shapes identical.

**Illustrative**
If applicable, add screenshots or minimal examples to help explain your problem.

**Version Info**
latest at the time

**Additional comments**
Squeezing the HeAT array after reading or adding `ndmin=2` to `loadtxt` makes it the same (see "ndmin" arg here https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html)

@coquelin77 Not sure if this is really an issue, just an observation.

**Comment by mrfh92** [comment]
See #900, #1140 for current goals regarding load functionality.  
Reviewed within #1109
