### ISSUE TITLE
Dot product with 2D dot 1D DNDarrays

### ISSUE THREAD

**Issue by coquelin77** [helmholtz-analytics/heat#817]
**Feature functionality**
Add functionality for passing in a vector as an argument for `dot`.

**Comment by mtar** [comment]
Do you have an example?

**Comment by coquelin77** [comment]
for this error it was a simple case of dot only working for either 1D x 1D or 2D x 2D. it wasnt an bug that was thrown but an oversight during implementation. The error thrown was a NotImplementedError
