### ISSUE TITLE
Benchmark `ht.cluster.kmeans` vs `dislib.cluster.KMeans` 

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#869]
**Feature functionality**
- Expand our benchmarks to compare Heat with [dislib](https://github.com/bsc-wdc/dislib) 
E.g. https://github.com/bsc-wdc/dislib/blob/master/notebooks/tutorial.ipynb

**Additional context**
Part of the [eFlows4HPC](https://eflows4hpc.eu/) effort

**Comment by mrfh92** [comment]
Efforts to compare with other libraries have been moved to a different repository 
(on helmholtz.codebase) and will be tracked there (at least during development)

Therefore, closed within #1109
