### ISSUE TITLE
Implement missing functionalities in `ht.divide` (`out`, `where`)

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#870]
**Feature functionality**
Enable usage of kwargs `out`, `where`

see https://numpy.org/doc/stable/reference/generated/numpy.divide.html

**Comment by neosunhan** [comment]
Hi @ClaudiaComito, may I try working on this issue?

**Comment by ClaudiaComito** [comment]
Hi @neosunhan , sure, go ahead

**Comment by neosunhan** [comment]
Hi @ClaudiaComito, I have made a pull request that should fix this issue. Would appreciate your input on any further changes I need to make.
