### ISSUE TITLE
Put together requirements Ginko Performance Explorer

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#879]
**Feature functionality**

**Additional context**
Bust memory leaks

**Comment by Markus-Goetz** [comment]
A first (perhaps incomplete) list of requirements:

* There are pre-defined benchmarking test cases, measuring
** Strong-scaling compute/memory/time/speed-up
** Weak-scaling compute/memory/time/speed-up
** Different backends
* Benchmarkings are performed continouosly on every branch-to-master merge
* Measured results are stored and versioned
* All results can be visualized as tables and graphs (vector graphics)
* Old benchmarking versions can be accessed
* Two versions can be compared side-by-side
* The visualization are available as a publicly accessible website, linked in the repo and the documentation

**Comment by mrfh92** [comment]
As far as I understand this, this has been realized with our continuous benchmarking. 

Therefore, closed within #1109
