### ISSUE TITLE
Add custom __str__ and __repr__ functions for tensors

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#89]
Currently, we are using the print functions of pytorch to print tensors to standard out.

Implement a custom version that deals with distributed tensors

**Comment by ClaudiaComito** [comment]
I'm giving up this Issue as I'd rather focus on the higher-level algorithms. @simon-schmitz would you like to take it on?

**Comment by simon-schmitz** [comment]
I can take it on @ClaudiaComito. Is there already some code and/or more information on this issue?

**Comment by Markus-Goetz** [comment]
Bump. What is the status on this?

**Comment by simon-schmitz** [comment]
Unfortunately I won't get time to work on this anytime soon. So far I don't have decent code for this. If the issue is urgent I'd suggest to assign it to somebody else. Otherwise I could tackle this again at some point in the next month.
