### ISSUE TITLE
`matmul` on multidimensional arrays

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#890]
**Description**
Matmul does not work on distributed arrays with more than 2 dimensions.

**To Reproduce**
1. Which module/class/function is affected?
linalg.matmul
2. What are the circumstances under which the bug appears?
dim > 2
3. What is the exact error message / erroneous behavior?
depends on split value
ValueError: If the last dimension of a (4) is not the same size as the second-to-last dimension of b. (4)
ZeroDivisionError: integer division or modulo by zero
mpi4py.MPI.Exception: MPI_ERR_TRUNCATE: message truncated
NotImplementedError: splits > 1 not implemented

**Expected behavior**
Matrix multiplication of the last two dimensions 

**Version Info**
main

**Comment by AsRaNi1** [comment]
@ClaudiaComito can i take this issue?

**Comment by mrfh92** [comment]
moved the relevant content to #1104; close this issue within #1109 since #890 is contained as a special case in #1104.

**Comment by ClaudiaComito** [comment]
Reopening this as it is being addressed in a dedicated PR: #1261 by @FOsterfeld
