### ISSUE TITLE
Data distribution schemes

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#896]
Following discussions at the heat-dev meeting Dec 8 2021, proposed by @Markus-Goetz :

- Introduce a new member to DNDarrays called e.g. distribution
- The distribution member holds an object of a subclass of Distribution
- Well-known Distribution subclasses are: 1D uniform data chunking (current implementation), nD block cyclic, arbitrary data locations (think lshape map for everything)
- If two data distributions of tensors match, i.e. are identical, then you can perform operations as currently done, e.g. by combining node-local portitions in a binary op
- Should the data distribution not(!) match, a function, e.g. called merge, combines all data distributions of the operands into a data distribution for the operation result
- Merging the data distribution is the difficult part and should optimally map back to simple data distribution and not allow arbitary chunk (see Dask)

**Comment by mrfh92** [comment]
In principle, this could be of interest, of course. However, this has not been addressed by PRs and/or discussions since being opened. 
Therefore, closed within #1109
