### ISSUE TITLE
Implement `ht.broadcast_shapes`

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#904]
**Related**
#891 

The `heat` function `stride_tricks.broadcast_shape`  differs unnecessarily from its numpy and torch counterparts:
1.   naming (heat `broadcast_shape` vs. numpy/torch `broadcast_shapes`)
2.  calling (`ht.stride_tricks.broadcast_shape()` vs.  `np.broadcast_shapes()` or `torch.broadcast_shapes()`)
3. arguments: `ht.stride_tricks.broadcast_shape` only takes 2 shapes as arguments, no limit on the numpy/torch side

**Feature functionality**

`ht.broadcast_shapes` should behave exactly like `np.broadcast_shapes`, i.e. return a shape as tuple - while using `torch.broadcast_shapes` under the hood for GPU compatibility

**ADDENDUM:**  `broadcast_shapes` is only available starting torch 1.8.0 and numpy 1.20. Doh!

**Comment by ClaudiaComito** [comment]
This is still open and necessary. Since Heat v1.3.0 we have adopted  NEP 29 (see #1146  ) and dropped support for torch<1.8 and numpy<1.20, so nothing stands in the way of implementing `ht.broadcast_shapes`

**Comment by samadpls** [comment]
Hello @ClaudiaComito, may I take work on this issue? Could you please assign it to me?

**Comment by ClaudiaComito** [comment]
Nice @samadpls , go ahead!
