### ISSUE TITLE
Implement gaussian_kde()

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#921]
**Feature functionality**
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html

**Additional context**
Distributed & parallel implementations e.g. [Zheng 2013](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjW84C0h5H2AhUPS_EDHc3QCRcQFnoECAIQAQ&url=https%3A%2F%2Fwww.cs.utah.edu%2F~jeffp%2Fpapers%2Fkde-big.pdf&usg=AOvVaw1vmO5lc2dPHZ8CedhEkOvq)

**Comment by mrfh92** [comment]
Stil interesting. 

Reviewed within #1109
