### ISSUE TITLE
implement index_put function

### ISSUE THREAD

**Issue by ben-bou** [helmholtz-analytics/heat#973]
**Related**
Related to advanced indexing in the `setitem`.

**Feature functionality**
[See torch definition.](https://pytorch.org/docs/stable/generated/torch.Tensor.index_put_.html)
Essentially, its the same as advanced indexing, however with the option to deal with duplicate indices by accumulating them.
(Maybe different binops besides addition could also be supported)

**Additional context**

**Comment by ClaudiaComito** [comment]
I'm going to close this for now, happy to reopen if demand is there

---
Reviewed within #1109
