### ISSUE TITLE
Introduce Onboarding section on README

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#979]
Our `Getting started` information is quite scattered across the README and other documents. 

Identify gaps, summarize available info into a compact and potentially testable (via GitHub Actions) section of the README.

@bducos will create a new branch and draft PR, afterwards all of our new contributors are very welcome to chip in:  @AmirTouilPU  @neosunhan @SaiSuraj27 @shahpratham @tewodros18 @Mystic-Slice @JuanPedroGHM

**Comment by coquelin77** [comment]
furthermore, it would be nice to have a short section about how to launch MPI programs. i.e. this is how to launch a code with multiple processes on SLURM (`srun`/`sbatch`) or you can run it locally with `mpirun`/`mpiexec`. 

something like this may be useful for new people who are unfamiliar with MPI codes

**Comment by ClaudiaComito** [comment]
This is done, though needs constant updates. See #1186
