### ISSUE TITLE
Limit matrix testing to relevant use cases and expand testing to Python 3.9

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#980]
Currently, our CI matrix is triggered when any PR is approved, and tests Heat with a combination of pytorch versions and Python 3.7 and 3.8.

Upgrades:

- Expand CI matrix to test with Python 3.9 as well  
- Limit triggers to PRs that actually modify the codebase (leave out tutorial, docs etc.)

_As discussed in meeting June 8th 2022 with @mtar , @JuanPedroGHM , @bhagemeier_

**Comment by mtar** [comment]
Workflow is skipped if the PR contains a specific string
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by ClaudiaComito** [comment]
this is closed! 👍🏼
